import type { PlaceSource } from '../../../types/place-source.ts';

export const GYEONGGI_NORTH_PLACES = [
  {
    id: 'gyeonggi-north-ilovemom-tanhyeon',
    name: '탄현위브더제니스 아이러브맘카페',
    region: 'gyeonggi-north',
    subRegion: '고양시 일산서구',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://www.echild.or.kr/m4/sub3.asp?play_area=%ED%83%84%ED%98%84%EC%9C%84%EB%B8%8C%EB%8D%94%EC%A0%9C%EB%8B%88%EC%8A%A4',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%83%84%ED%98%84%EC%9C%84%EB%B8%8C%EB%8D%94%EC%A0%9C%EB%8B%88%EC%8A%A4%20%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EC%9D%BC%EC%82%B0%EC%84%9C%EA%B5%AC%20%EC%9D%BC%ED%98%84%EB%A1%9C%2097-11',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '공동주택 연계형 공공 아이러브맘카페. 영유아와 보호자가 함께 머무는 생활권 실내 육아 공간이다.',
    address: '경기도 고양시 일산서구 일현로 97-11',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-north-uijeongbu-ilovemom-cafe',
    name: '의정부시 아이러브맘카페',
    region: 'gyeonggi-north',
    subRegion: '의정부시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://icare.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9D%98%EC%A0%95%EB%B6%80%EC%8B%9C%20%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%9D%98%EC%A0%95%EB%B6%80%EC%8B%9C%20%EC%8B%A0%ED%9D%A5%EB%A1%9C%20198%20%EB%8D%95%EC%95%94%EB%B9%8C%EB%94%A9%203%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '의정부 시내권 공공 아이러브맘카페. 어린이집을 이용하지 않는 영유아와 보호자가 함께 이용하는 실내 공간이다.',
    address: '경기도 의정부시 신흥로 198 덕암빌딩 3층',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-north-toy-library-okjeong',
    name: '장난감도서관 옥정점',
    region: 'gyeonggi-north',
    subRegion: '양주시',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.yjscic.or.kr/index.asp',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9E%A5%EB%82%9C%EA%B0%90%EB%8F%84%EC%84%9C%EA%B4%80%20%EC%98%A5%EC%A0%95%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%96%91%EC%A3%BC%EC%8B%9C%20%EC%98%A5%EC%A0%95%EB%A1%9C%20397-7%20%EC%98%A5%EC%A0%951%EB%8F%99%ED%96%89%EC%A0%95%EB%B3%B5%EC%A7%80%EC%84%BC%ED%84%B0%202%EC%B8%B5',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '양주시육아종합지원센터에서 운영하는 옥정권 장난감도서관. 대여형 실내 육아 인프라로 분류한다.',
    address: '경기도 양주시 옥정로 397-7 옥정1동행정복지센터 2층',
    rainFriendly: true,
    stayMinutes: 30,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-north-first-garden',
    name: '퍼스트가든',
    region: 'gyeonggi-north',
    subRegion: '고양시',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.firstgarden.co.kr/content/guide',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%8D%BC%EC%8A%A4%ED%8A%B8%EA%B0%80%EB%93%A0%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EC%9D%BC%EC%82%B0%EB%8F%99%EA%B5%AC%20%ED%83%91%EC%82%AD%EA%B3%A8%EA%B8%B8%20260',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '정원형 테마파크. 36개월 미만 무료입장, 유모차 대여, 주차장 주소가 공식 안내에서 확인된다.',
    address: '경기도 고양시 일산동구 탑삭골길 260',
    rainFriendly: false,
    stayMinutes: 180,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-hyundai-motorstudio-goyang',
    name: '현대 모터스튜디오 고양',
    region: 'gyeonggi-north',
    subRegion: '고양시',
    category: 'experience',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://motorstudio.hyundai.com/goyang/ln/main.do',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%98%84%EB%8C%80%20%EB%AA%A8%ED%84%B0%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4%20%EA%B3%A0%EC%96%91%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EC%9D%BC%EC%82%B0%EC%84%9C%EA%B5%AC%20%ED%82%A8%ED%85%8D%EC%8A%A4%EB%A1%9C%20217-6',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'semi_verified',
    description:
      '자동차 전시와 체험 프로그램을 운영하는 실내 체험 공간. 자동차를 좋아하는 아이와 비 오는 날 묶기 좋다.',
    address: '경기도 고양시 일산서구 킨텍스로 217-6',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-toykingdom-play-goyang',
    name: '토이킹덤플레이 스타필드 고양',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/goyang/entertainment/toyKingdomPlay.do',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%86%A0%EC%9D%B4%ED%82%B9%EB%8D%A4%ED%94%8C%EB%A0%88%EC%9D%B4%20%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%20%EA%B3%A0%EC%96%91%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EB%8D%95%EC%96%91%EA%B5%AC%20%EA%B3%A0%EC%96%91%EB%8C%80%EB%A1%9C%201955',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '36개월~13세 대상 키즈 체험 파크. 스타필드 고양 실내 동선에서 장난감 체험과 놀이를 함께 묶기 좋다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    priceInfo: '36개월~13세 15,000원(2시간) / 18,000원(3시간)',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-bricklive-goyang',
    name: '브릭라이브 스타필드 고양',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'experience',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/goyang/entertainment/brickLive.do',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%B8%8C%EB%A6%AD%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%20%EA%B3%A0%EC%96%91%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EB%8D%95%EC%96%91%EA%B5%AC%20%EA%B3%A0%EC%96%91%EB%8C%80%EB%A1%9C%201955',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '36개월 이상 대상 브릭 전시·체험 공간. 만들기와 전시 관람을 함께 하는 실내 체험 후보로 둔다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    priceInfo: '어린이 16,000원 / 성인 10,000원',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-ikea-goyang-smaland',
    name: 'IKEA 고양점 스몰란드',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ikea.com/kr/ko/stores/goyang/smaland-puba30128d2',
    naverMapUrl: 'https://map.naver.com/p/search/IKEA%20%EA%B3%A0%EC%96%91%EC%A0%90%20%EC%8A%A4%EB%AA%B0%EB%9E%80%EB%93%9C%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EB%8D%95%EC%96%91%EA%B5%AC%20%EA%B6%8C%EC%9C%A8%EB%8C%80%EB%A1%9C%20420',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      'IKEA 고양점 내 무료 키즈 플레이룸. 키와 배변 독립 조건이 있어 미취학 후반~초등 저학년에 적합하다.',
    address: '경기도 고양시 덕양구 권율대로 420',
    priceInfo: '무료 / 하루 1회 1시간',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-jamjam-kidsroom-hwajeong',
    name: '잼잼키즈룸 화정점',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%9E%BC%EC%9E%BC%ED%82%A4%EC%A6%88%EB%A3%B8-%ED%99%94%EC%A0%95%EC%A0%90-tvdq2fzri3na/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9E%BC%EC%9E%BC%ED%82%A4%EC%A6%88%EB%A3%B8%20%ED%99%94%EC%A0%95%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EB%8D%95%EC%96%91%EA%B5%AC%20%ED%99%94%EC%8B%A0%EB%A1%9C%20267',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '프리미엄 대관형 키즈룸. 놀이시설, 주차, 인원 안내가 점주 채널과 네이버 플레이스에서 교차 확인된다.',
    address: '경기도 고양시 덕양구 화신로 267',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-webounce-yangju',
    name: '위바운스 키즈카페',
    region: 'gyeonggi-north',
    subRegion: '양주시',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%9C%84%EB%B0%94%EC%9A%B4%EC%8A%A4-%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98-g6wj6sv5aix6/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9C%84%EB%B0%94%EC%9A%B4%EC%8A%A4%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%96%91%EC%A3%BC%EC%8B%9C%20%EA%B3%A0%EC%95%94%EA%B8%B8%20358%20%EC%9D%B8%EC%95%84%ED%94%84%EB%9D%BC%EC%9E%90%20%EC%A7%80%ED%95%98%202%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '덕정동 트램폴린 키즈카페. 당근 업체 프로필에서 운영시간, 전화, 가격, 주소가 확인된다.',
    address: '경기도 양주시 고암길 358 인아프라자 지하 2층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-kikikidspool',
    name: '키키키즈풀',
    region: 'gyeonggi-north',
    subRegion: '의정부시',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/business-profiles/%ED%82%A4%ED%82%A4%ED%82%A4%EC%A6%88%ED%92%80-%EB%8F%99%EB%84%A4%EC%97%85%EC%B2%B4-%ED%82%A4%ED%82%A4%ED%82%A4%EC%A6%88%ED%92%80-de756df85f024a6ca37aef2c0a02394d/',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%82%A4%ED%82%A4%ED%82%A4%EC%A6%88%ED%92%80%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%9D%98%EC%A0%95%EB%B6%80%EC%8B%9C%20%EC%9A%A9%EB%AF%BC%EB%A1%9C237%EB%B2%88%EA%B8%B8%2011',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '온수 키즈풀과 파티룸을 결합한 예약형 공간. 물놀이 키즈카페 후보로 관리한다.',
    address: '경기도 의정부시 용민로237번길 11',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-in-the-pool',
    name: '인더풀',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/business-post/%EC%B6%94%EC%9B%8C%EC%A7%88%EB%95%90-%EC%8B%A4%EB%82%B4%EC%88%98%EC%98%81%EC%9E%A5%EC%9D%B4%EC%A3%A0-642588ec36c1f04045dadf2a/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9D%B8%EB%8D%94%ED%92%80%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EB%8D%95%EC%96%91%EA%B5%AC%20%EC%8B%A0%EC%9B%90%EB%8F%99',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '신원동 키즈풀·파티룸 후보. 비즈 소식에서 예약 시간과 시설 구성, 네이버 예약 안내가 확인된다.',
    address: '경기도 고양시 덕양구 신원동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote: '상세 도로명주소는 발행 전 재확인이 필요하다.',
  },
  {
    id: 'gyeonggi-north-sangsang-kidsroom-paju',
    name: '상상키즈룸 파주운정점',
    region: 'gyeonggi-north',
    subRegion: '파주시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%83%81%EC%83%81%ED%82%A4%EC%A6%88%EB%A3%B8-%ED%8C%8C%EC%A3%BC%EC%9A%B4%EC%A0%95%EC%A0%90-3fjbbttcmqzy/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%83%81%EC%83%81%ED%82%A4%EC%A6%88%EB%A3%B8%20%ED%8C%8C%EC%A3%BC%EC%9A%B4%EC%A0%95%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%8C%8C%EC%A3%BC%EC%8B%9C%20%EB%8B%A4%EC%9C%A8%EB%8F%99',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '외부음식 반입과 무료주차 신호가 있는 프라이빗 키즈룸. 파주 운정권 예약형 공간 후보로 둔다.',
    address: '경기도 파주시 다율동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote: '상세 주소와 예약 링크는 발행 전 재확인이 필요하다.',
  },
  {
    id: 'gyeonggi-north-jackson-nines-ilsan',
    name: '잭슨나인스 일산점',
    region: 'gyeonggi-north',
    subRegion: '고양시 일산서구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.jsnines.com/jackson-ilsan',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9E%AD%EC%8A%A8%EB%82%98%EC%9D%B8%EC%8A%A4%20%EC%9D%BC%EC%82%B0%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EC%9D%BC%EC%82%B0%EC%84%9C%EA%B5%AC%20%ED%98%B8%EC%88%98%EB%A1%9C%20817%20%EB%A0%88%EC%9D%B4%ED%82%A8%EC%8A%A4%EB%AA%B0%203%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '9개 테마 공간을 갖춘 실내 테마파크형 키즈카페. 공연, 게임, 액션존을 함께 이용하는 가족형 공간이다.',
    address: '경기도 고양시 일산서구 호수로 817 레이킨스몰 3층',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-north-pororo-park-ilsan-kintex',
    name: '뽀로로파크 일산킨텍스점',
    region: 'gyeonggi-north',
    subRegion: '고양시 일산서구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.pororopark.com/information/serviceHours.php',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%BD%80%EB%A1%9C%EB%A1%9C%ED%8C%8C%ED%81%AC%20%EC%9D%BC%EC%82%B0%ED%82%A8%ED%85%8D%EC%8A%A4%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%A0%EC%96%91%EC%8B%9C%20%EC%9D%BC%EC%82%B0%EC%84%9C%EA%B5%AC%20%ED%82%A8%ED%85%8D%EC%8A%A4%EB%A1%9C%20217-59',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '뽀로로 캐릭터 세계관을 기반으로 한 일산권 실내 키즈파크. 미취학 아동과 초등 저학년까지 묶기 좋은 캐릭터형 테마 키즈카페다.',
    address: '경기도 고양시 일산서구 킨텍스로 217-59',
    priceInfo: '유료 / 지점·시즌별 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 이용시간 페이지와 리서치 문서에서 지점 운영 신호를 확인했다. 요금과 주차 지원은 발행 전 재확인 필요.',
  },
  {
    id: 'jeongok-prehistory-museum',
    name: '전곡선사박물관',
    region: 'gyeonggi-north',
    subRegion: '연천군',
    category: 'museum',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://jgpm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13371441',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '선사 유적지와 함께 둘러보기 좋은 체험형 박물관. 실내 전시와 야외 동선을 함께 계획하기 좋다.',
    address: '경기도 연천군 전곡읍 평화로 443번길 2',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '교육 프로그램은 별도 예약이 있을 수 있어 방문 전 공식 일정을 확인하는 편이 안전하다.',
    thumbnailImage: '/images/places/jeongok-prehistory-museum.webp',
  },
  {
    id: 'silhak-museum',
    name: '실학박물관',
    region: 'gyeonggi-north',
    subRegion: '남양주시',
    category: 'museum',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://silhak.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12967430',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '실학과 과학사를 함께 풀어내는 공공 박물관. 실내 전시 위주로 천천히 보기 좋은 가족 관람형 공간.',
    address: '경기도 남양주시 조안면 다산로747번길 16',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '무료 관람이지만 휴관일과 교육 프로그램 일정은 공식 홈페이지에서 다시 확인하는 편이 좋다.',
    thumbnailImage: '/images/places/silhak-museum.webp',
  },
  {
    id: 'champion-1250x-goyang',
    name: '챔피언1250X 스타필드 고양',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.starfield.co.kr/goyang/entertainment/champion1250.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1029881605',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '클라이밍과 어드벤처 구조물이 중심인 대형 실내놀이터. 보호자 동반 기준으로 2시간 이용하기 좋다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    priceInfo: '주중 25,000원 / 주말 29,000원 / 2시간',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '스타필드 고양 내 위치. 키즈 체험형 실내놀이터 성격이 강해 활동량이 많은 아이에게 잘 맞는다.',
    thumbnailImage: '/images/places/champion-1250x-goyang.webp',
  },
  {
    id: 'wonder-village-goyang',
    name: '원더빌리지 & 카페 드 아쿠아',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.starfield.co.kr/goyang/entertainment/wondervillage.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1033377158',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '오감 체험형 공간과 카페 동선을 함께 묶은 가족형 실내 놀이 공간. 스타필드 고양에서 날씨 영향을 덜 받고 오래 머물기 좋다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    operatingHours: '10:00-22:00',
    priceInfo:
      '대인 12,000원 / 소인 19,000원 / 패키지 17,000원~24,000원 / 24개월 미만 무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
    editorNote:
      '중학생 미만 소인은 보호자 동반 입장이 필요하다. 스타필드 고양 주차장 이용 가능.',
    thumbnailImage: '/images/places/wonder-village-goyang.webp',
  },
  {
    id: 'goyang-ilovemom-cafe-hwajeong',
    name: '화정육아종합지원센터 아이러브맘카페',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://www.echild.or.kr/m4/sub3.asp?play_area=%ED%99%94%EC%A0%95%EC%9C%A1%EC%95%84%EC%A2%85%ED%95%A9%EC%A7%80%EC%9B%90%EC%84%BC%ED%84%B0',
    naverMapUrl: 'https://map.naver.com/p/entry/place/34784837',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '영유아와 보호자가 함께 머무는 공공 아이러브맘카페. 덕양구 생활권에서 짧게 들르기 좋은 실내 육아 거점이다.',
    address: '경기도 고양시 덕양구 화신로 325 고양특례시육아종합지원센터',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '네이버 지도는 센터 대표 장소를 연결했다. 상세 층수와 회차 운영은 방문 전 공식 안내를 다시 확인하는 편이 안전하다.',
  },
  {
    id: 'guri-ilovemom-cafe-inchang',
    name: '아이러브맘카페(인창점)',
    region: 'gyeonggi-north',
    subRegion: '구리시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://guricenter.go.kr/text/s3_1_1.php',
    naverMapUrl: 'https://map.naver.com/p/entry/place/33892567',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '구리시 생활권에서 이용하기 쉬운 공공 아이러브맘카페. 영유아와 보호자가 함께 머물며 짧게 놀기 좋은 실내 공간이다.',
    address: '경기도 구리시 동구릉로53번길 34 4층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '구리시육아종합지원센터 안내 페이지와 네이버 지도에서 위치를 교차 확인했다.',
  },
  {
    id: 'guri-isarang-playground-galmae',
    name: '아이사랑놀이터(갈매점)',
    region: 'gyeonggi-north',
    subRegion: '구리시',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://guricenter.go.kr/text/s4_1_1.php',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1600058395',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '갈매 생활권에서 이용하기 좋은 공공 실내 놀이터. 부모와 영유아가 함께 머물며 가볍게 놀기 좋은 동네 거점이다.',
    address: '경기도 구리시 산마루로 18 하나로프라자 8층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공식 안내와 네이버 지도 모두 갈매아이사랑놀이터 표기를 사용한다.',
  },
  {
    id: 'paju-ilovemom-cafe',
    name: '파주시 아이러브맘카페',
    region: 'gyeonggi-north',
    subRegion: '파주시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://gyeonggi.childcare.go.kr/lgyeonggi/d10_20000/d10_20061/d10_20063.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/36816859',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '문산 생활권 부모와 영유아가 함께 이용하는 공공 아이러브맘카페. 실내 육아 동선에서 짧게 들르기 좋은 생활권 거점이다.',
    address: '경기도 파주시 문산읍 통일로 1680 문산행복센터 4층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '네이버 지도에는 파주시육아종합지원센터 아이러브맘카페로 노출된다.',
  },
  {
    id: 'gyeonggi-northern-childrens-museum',
    name: '경기북부어린이박물관',
    region: 'gyeonggi-north',
    subRegion: '동두천시',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://ngcm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37881828',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '숲과 생태를 주제로 몸으로 체험하는 경기북부 대표 어린이박물관. 실내 전시와 야외 놀이터를 함께 묶기 좋다.',
    address: '경기도 동두천시 평화로2910번길 46',
    operatingHours: '10:00-18:00',
    priceInfo: '4,000원 / 12개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '100% 온라인 사전예약제로 운영된다. 영아 놀이터와 유모차 대여 등 저연령 편의시설이 함께 확인됐다.',
  },
  {
    id: 'goyang-children-museum',
    name: '고양어린이박물관',
    region: 'gyeonggi-north',
    subRegion: '고양시',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.goyangcm.or.kr/product/ticketguide',
    naverMapUrl: 'https://map.naver.com/p/entry/place/33997463',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '회차제로 운영하는 고양 대표 어린이 체험 박물관. 저연령부터 초등 저학년까지 두루 묶기 좋은 실내 나들이 공간이다.',
    address: '경기도 고양시 덕양구 화중로 26',
    operatingHours: '10:00-17:30',
    priceInfo: '일반 회차 예매 5,000원 / 36개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '100% 온라인 사전예약제다. 주차장 협소 안내가 있어 주말에는 시간 여유를 두는 편이 좋다.',
  },
  {
    id: 'uijeongbu-public-playground-2',
    name: '의정부 모두의 놀이터 2호점',
    region: 'gyeonggi-north',
    subRegion: '의정부시',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://icare.or.kr/text/s6_1.php',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1894687631',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '놀이실과 장난감도서관 기능을 함께 둔 공공 실내놀이터. 의정부 도심 생활권에서 짧게 들르기 좋다.',
    address: '경기도 의정부시 둔야로 9 2층',
    priceInfo: '회원·이용안내 확인 필요',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공식 이용안내에 이용대상과 회원 기준이 노출된다. 세부 요금과 회차는 방문 전 다시 확인하는 편이 안전하다.',
  },
  {
    id: 'uijeongbu-public-playground-3',
    name: '롯데mom편한 모두의 놀이터 3호점',
    region: 'gyeonggi-north',
    subRegion: '의정부시',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://icare.or.kr/text/s1_5_4.php?device=pc',
    naverMapUrl: 'https://map.naver.com/p/entry/place/2082332258',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '롯데 연계형 공공 실내놀이터로 영유아 생활권 놀이 거점 성격이 강한 시설. 짧은 회차 중심 방문에 잘 맞는다.',
    address: '경기도 의정부시 가능로152번길 14 1층',
    priceInfo: '지점 문의',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '센터 공식 오시는 길 페이지에서 지점 주소를 확인했다. 세부 이용 기준은 방문 전 지점 안내를 다시 보는 편이 좋다.',
  },
  {
    id: 'okjeong-toy-library',
    name: '장난감도서관 옥정점',
    region: 'gyeonggi-north',
    subRegion: '양주시',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.yjscic.or.kr/index.asp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1910743938',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '장난감 대여 중심으로 운영하는 공공 육아 지원 거점. 옥정 생활권에서 실내 육아 보조 동선으로 쓰기 좋다.',
    address: '경기도 양주시 옥정로 397-7 옥정1동행정복지센터 2층',
    priceInfo: '회원제 운영',
    rainFriendly: true,
    stayMinutes: 30,
    operatorType: 'public',
    editorNote:
      '양주시육아종합지원센터 공식 메인에 옥정점 주소와 이용시간이 노출된다.',
  },
  {
    id: 'first-garden',
    name: '퍼스트가든',
    region: 'gyeonggi-north',
    subRegion: '고양시',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.firstgarden.co.kr/content/guide',
    naverMapUrl: 'https://map.naver.com/p/entry/place/194606488',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '정원 산책과 야간 조명을 함께 즐길 수 있는 대형 정원형 테마파크. 계절별 야외 나들이 코스로 묶기 좋다.',
    address: '경기도 고양시 일산동구 탑삭골길 260',
    priceInfo: '36개월 미만 무료입장',
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 180,
    operatorType: 'commercial',
    editorNote:
      '공식 이용요금 페이지에 36개월 미만 무료, 유모차 대여, 주차장 안내가 함께 노출된다. 운영시간은 계절과 행사에 따라 변동 가능하다.',
  },
] satisfies PlaceSource[];
