import type { PlaceSource } from '../../../types/place-source.ts';

export const GYEONGGI_NORTH_PLACES = [
  {
    id: 'jeongok-prehistory-museum',
    name: '전곡선사박물관',
    region: 'gyeonggi-north',
    subRegion: '연천군',
    category: 'museum',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://jgpm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13371441',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '선사 유적지와 함께 둘러보기 좋은 체험형 박물관. 실내 전시와 야외 동선을 함께 계획하기 좋다.',
    address: '경기도 연천군 전곡읍 평화로 443번길 2',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '교육 프로그램은 별도 예약이 있을 수 있어 방문 전 공식 일정을 확인하는 편이 안전하다.',
    thumbnailImage: '/images/places/jeongok-prehistory-museum.webp',
  },
  {
    id: 'silhak-museum',
    name: '실학박물관',
    region: 'gyeonggi-north',
    subRegion: '남양주시',
    category: 'museum',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://silhak.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12967430',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '실학과 과학사를 함께 풀어내는 공공 박물관. 실내 전시 위주로 천천히 보기 좋은 가족 관람형 공간.',
    address: '경기도 남양주시 조안면 다산로747번길 16',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '무료 관람이지만 휴관일과 교육 프로그램 일정은 공식 홈페이지에서 다시 확인하는 편이 좋다.',
    thumbnailImage: '/images/places/silhak-museum.webp',
  },
  {
    id: 'champion-1250x-goyang',
    name: '챔피언1250X 스타필드 고양',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.starfield.co.kr/goyang/entertainment/champion1250.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1029881605',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '클라이밍과 어드벤처 구조물이 중심인 대형 실내놀이터. 보호자 동반 기준으로 2시간 이용하기 좋다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    priceInfo: '주중 25,000원 / 주말 29,000원 / 2시간',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '스타필드 고양 내 위치. 키즈 체험형 실내놀이터 성격이 강해 활동량이 많은 아이에게 잘 맞는다.',
    thumbnailImage: '/images/places/champion-1250x-goyang.webp',
  },
  {
    id: 'wonder-village-goyang',
    name: '원더빌리지 & 카페 드 아쿠아',
    region: 'gyeonggi-north',
    subRegion: '고양시 덕양구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.starfield.co.kr/goyang/entertainment/wondervillage.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1033377158',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '오감 체험형 공간과 카페 동선을 함께 묶은 가족형 실내 놀이 공간. 스타필드 고양에서 날씨 영향을 덜 받고 오래 머물기 좋다.',
    address: '경기도 고양시 덕양구 고양대로 1955',
    operatingHours: '10:00-22:00',
    priceInfo:
      '대인 12,000원 / 소인 19,000원 / 패키지 17,000원~24,000원 / 24개월 미만 무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
    editorNote:
      '중학생 미만 소인은 보호자 동반 입장이 필요하다. 스타필드 고양 주차장 이용 가능.',
    thumbnailImage: '/images/places/wonder-village-goyang.webp',
  },
  {
    id: 'gyeonggi-northern-childrens-museum',
    name: '경기북부어린이박물관',
    region: 'gyeonggi-north',
    subRegion: '동두천시',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://ngcm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37881828',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '숲과 생태를 주제로 몸으로 체험하는 경기북부 대표 어린이박물관. 실내 전시와 야외 놀이터를 함께 묶기 좋다.',
    address: '경기도 동두천시 평화로2910번길 46',
    operatingHours: '10:00-18:00',
    priceInfo: '4,000원 / 12개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '100% 온라인 사전예약제로 운영된다. 영아 놀이터와 유모차 대여 등 저연령 편의시설이 함께 확인됐다.',
  },
  {
    id: 'goyang-children-museum',
    name: '고양어린이박물관',
    region: 'gyeonggi-north',
    subRegion: '고양시',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.goyangcm.or.kr/product/ticketguide',
    naverMapUrl: 'https://map.naver.com/p/entry/place/33997463',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '회차제로 운영하는 고양 대표 어린이 체험 박물관. 저연령부터 초등 저학년까지 두루 묶기 좋은 실내 나들이 공간이다.',
    address: '경기도 고양시 덕양구 화중로 26',
    operatingHours: '10:00-17:30',
    priceInfo: '일반 회차 예매 5,000원 / 36개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '100% 온라인 사전예약제다. 주차장 협소 안내가 있어 주말에는 시간 여유를 두는 편이 좋다.',
  },
] satisfies PlaceSource[];
