import type { PlaceSource } from '../../../types/place-source.ts';

export const SEOUL_PLACES = [
  {
    id: 'seoul-kids-craft-village',
    name: '서울형 키즈카페 시립 공예마을점',
    region: 'seoul',
    subRegion: '종로구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=JN251201&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%84%9C%EC%9A%B8%ED%98%95%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20%EC%8B%9C%EB%A6%BD%20%EA%B3%B5%EC%98%88%EB%A7%88%EC%9D%84%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%A2%85%EB%A1%9C%EA%B5%AC%20%EC%9C%A8%EA%B3%A1%EB%A1%9C3%EA%B8%B8%204%20%EC%84%9C%EC%9A%B8%EA%B3%B5%EC%98%88%EB%B0%95%EB%AC%BC%EA%B4%80%20%EC%96%B4%EB%A6%B0%EC%9D%B4%EB%B0%95%EB%AC%BC%EA%B4%80%20%EA%B5%90%EC%9C%A1%EB%8F%99%202~3%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '서울공예박물관 어린이박물관 교육동에 있는 0~9세 대상 공공형 키즈카페. 영아 동반 실내 나들이 후보로 묶기 좋다.',
    address: '서울특별시 종로구 율곡로3길 4 서울공예박물관 어린이박물관 교육동 2~3층',
    priceInfo: '지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
  },
  {
    id: 'seoul-sangsangnara-happy-plus-cafe',
    name: '행복플러스카페(서울상상나라 내)',
    region: 'seoul',
    subRegion: '광진구',
    category: 'culture',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.seoulchildrensmuseum.org/reservation/viewConvenience.do',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%96%89%EB%B3%B5%ED%94%8C%EB%9F%AC%EC%8A%A4%EC%B9%B4%ED%8E%98(%EC%84%9C%EC%9A%B8%EC%83%81%EC%83%81%EB%82%98%EB%9D%BC%20%EB%82%B4)%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B4%91%EC%A7%84%EA%B5%AC%20%EB%8A%A5%EB%8F%99%EB%A1%9C%20216%20%EC%96%B4%EB%A6%B0%EC%9D%B4%EB%8C%80%EA%B3%B5%EC%9B%90%20%EB%82%B4',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '서울상상나라 편의시설로 연결되는 시설 연계형 가족 카페. 어린이대공원·서울상상나라 방문 동선과 함께 쓰기 좋다.',
    address: '서울특별시 광진구 능동로 216 어린이대공원 내',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'seoul-caliclub-cheongdam',
    name: '캘리클럽 청담점',
    region: 'seoul',
    subRegion: '강남구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://caliclub.kr/cheongdamclub',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%BA%98%EB%A6%AC%ED%81%B4%EB%9F%BD%20%EC%B2%AD%EB%8B%B4%EC%A0%90%20%EC%84%9C%EC%9A%B8%20%EA%B0%95%EB%82%A8%EA%B5%AC%20%EC%84%A0%EB%A6%89%EB%A1%9C%20832%20%EC%86%8C%EB%82%98%EB%AC%B4%20%EB%B9%8C%EB%94%A9%20%EC%A7%80%ED%95%98%202%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '24개월 이상부터 초등 저학년까지 이용하기 좋은 스포츠형 사설 실내놀이터. 활동량 많은 아이에게 맞는 키즈 스포츠 공간이다.',
    address: '서울 강남구 선릉로 832 소나무 빌딩 지하 2층',
    priceInfo: '2시간 기준 / 공식 페이지 확인',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-caliclub-gocheok',
    name: '캘리클럽 고척점',
    region: 'seoul',
    subRegion: '구로구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://caliclub.kr/55',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%BA%98%EB%A6%AC%ED%81%B4%EB%9F%BD%20%EA%B3%A0%EC%B2%99%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B5%AC%EB%A1%9C%EA%B5%AC%20%EA%B2%BD%EC%9D%B8%EB%A1%9C43%EA%B8%B8%2049%20C%EB%8F%99%201%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '아이파크몰 고척점에 있는 24개월 이상 대상 사설 실내놀이터. 쇼핑몰 동선과 함께 묶기 좋은 실내 활동 공간이다.',
    address: '서울특별시 구로구 경인로43길 49 C동 1층',
    priceInfo: '2시간 기준 / 공식 페이지 확인',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-sol-kids-land',
    name: '쏠키즈랜드',
    region: 'seoul',
    subRegion: '은평구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%8F%A0%ED%82%A4%EC%A6%88%EB%9E%9C%EB%93%9C-nghd5ced64ar/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%8F%A0%ED%82%A4%EC%A6%88%EB%9E%9C%EB%93%9C%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%9D%80%ED%8F%89%EA%B5%AC%20%EC%97%B0%EC%84%9C%EB%A1%9C3%EA%B8%B8%2040',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '60평대 공간과 놀이시설을 갖춘 프라이빗 대관형 키즈카페. 예약형 소규모 모임 후보로 관리한다.',
    address: '서울특별시 은평구 연서로3길 40',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-chouchou-poollace',
    name: '슈슈풀레이스',
    region: 'seoul',
    subRegion: '노원구',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%8A%88%EC%8A%88%ED%92%80%EB%A0%88%EC%9D%B4%EC%8A%A4-1983960/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%8A%88%EC%8A%88%ED%92%80%EB%A0%88%EC%9D%B4%EC%8A%A4%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EB%85%B8%EC%9B%90%EA%B5%AC%20%EB%88%84%EC%9B%90%EB%A1%9C%2020%203%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '워터룸과 파티룸 성격을 함께 가진 프라이빗 공간. 영유아 동반 예약형 물놀이 후보로 분류한다.',
    address: '서울특별시 노원구 누원로 20 3층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-dduddurang-nolja',
    name: '뚜뚜랑놀자',
    region: 'seoul',
    subRegion: '도봉구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EB%9A%9C%EB%9A%9C%EB%9E%91%EB%86%80%EC%9E%90-jx9f3d97g216/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%9A%9C%EB%9A%9C%EB%9E%91%EB%86%80%EC%9E%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EB%8F%84%EB%B4%89%EA%B5%AC%20%EB%8F%84%EB%B4%89%EB%A1%9C133%EA%B8%B8%2041',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '무인 대관형 키즈카페. 네이버 예약 시스템과 공식 SNS 운영 신호가 있어 발행 가능한 준검증 후보로 둔다.',
    address: '서울특별시 도봉구 도봉로133길 41',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-chakan-tokki-bugahyeon',
    name: '착한토끼 서대문북아현하우스',
    region: 'seoul',
    subRegion: '서대문구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%B0%A9%ED%95%9C%ED%86%A0%EB%81%BC-%EC%84%9C%EB%8C%80%EB%AC%B8%EB%B6%81%EC%95%84%ED%98%84%ED%95%98%EC%9A%B0%EC%8A%A4-p7o7pgo4a94v/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%B0%A9%ED%95%9C%ED%86%A0%EB%81%BC%20%EC%84%9C%EB%8C%80%EB%AC%B8%EB%B6%81%EC%95%84%ED%98%84%ED%95%98%EC%9A%B0%EC%8A%A4%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%84%9C%EB%8C%80%EB%AC%B8%EA%B5%AC%20%EC%8B%A0%EC%B4%8C%EB%A1%9C%20231',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '100% 예약제로 운영되는 무인 프라이빗 키즈카페. 소규모 가족 모임과 생일 모임 후보로 관리한다.',
    address: '서울특별시 서대문구 신촌로 231',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-karaplay',
    name: '카라플레이',
    region: 'seoul',
    subRegion: '동대문구',
    category: 'experience',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EC%B9%B4%EB%9D%BC%ED%94%8C%EB%A0%88%EC%9D%B4-1749023/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%B9%B4%EB%9D%BC%ED%94%8C%EB%A0%88%EC%9D%B4%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC%20%EB%8B%B5%EC%8B%AD%EB%A6%AC%EB%A1%9C30%EA%B8%B8%2044',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '북플레이 라운지형 키즈 공간. 일반 키즈카페보다 프로그램형 성격이 있어 체험시설로 분류한다.',
    address: '서울특별시 동대문구 답십리로30길 44',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-woorikkiri-dapsimni-sports',
    name: '우리끼리 키즈카페 스포츠마을 답십리점',
    region: 'seoul',
    subRegion: '동대문구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.daangn.com/kr/local-profile/5d8pyono2hbw/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%9A%B0%EB%A6%AC%EB%81%BC%EB%A6%AC%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20%EC%8A%A4%ED%8F%AC%EC%B8%A0%EB%A7%88%EC%9D%84%20%EB%8B%B5%EC%8B%AD%EB%A6%AC%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC%20%EC%A0%84%EB%86%8D%EB%A1%9C%2024%20%EA%B3%84%EB%A6%BC%EB%B9%8C%EB%94%A9%206%EC%B8%B5%20601%ED%98%B8',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '무인 대관형 스포츠마을 콘셉트 키즈카페. 예약제 실내 놀이공간으로 짧은 모임에 적합하다.',
    address: '서울특별시 동대문구 전농로 24 계림빌딩 6층 601호',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-kidsrun-sports-park-mokdong',
    name: '키즈런스포츠파크 목동점',
    region: 'seoul',
    subRegion: '양천구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=df032f21-89fd-4d3d-8013-1c5fcd5b19b8',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%82%A4%EC%A6%88%EB%9F%B0%EC%8A%A4%ED%8F%AC%EC%B8%A0%ED%8C%8C%ED%81%AC%20%EB%AA%A9%EB%8F%99%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%96%91%EC%B2%9C%EA%B5%AC%20%EB%AA%A9%EB%8F%99%EB%8F%99%EB%A1%9C%20401%20%EB%B6%80%EC%98%81%EA%B7%B8%EB%A6%B0%ED%83%80%EC%9A%B42%EC%B0%A8%20%EC%A7%80%ED%95%981%EC%B8%B5%20B101%ED%98%B8',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '1000평 규모로 소개된 대형 스포츠형 키즈카페. 카트존, 슬라이드, 편백놀이, 에어바운스 등 활동형 콘텐츠가 많다.',
    address: '서울특별시 양천구 목동동로 401 부영그린타운2차 지하1층 B101호',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-champion-1250x-yongsan',
    name: '챔피언1250X 아이파크몰 용산점',
    region: 'seoul',
    subRegion: '용산구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=a591d1ba-0412-46bf-bad0-d3707bdc7d16',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%B1%94%ED%94%BC%EC%96%B81250X%20%EC%95%84%EC%9D%B4%ED%8C%8C%ED%81%AC%EB%AA%B0%20%EC%9A%A9%EC%82%B0%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%9A%A9%EC%82%B0%EA%B5%AC%20%ED%95%9C%EA%B0%95%EB%8C%80%EB%A1%9C23%EA%B8%B8%2055%20%EC%95%84%EC%9D%B4%ED%8C%8C%ED%81%AC%EB%AA%B0%20%EB%A6%AC%EB%B9%99%ED%8C%8C%ED%81%AC%206%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '오르기, 뛰기, 매달리기 중심의 익스트림 어린이 스포츠클럽. 활동량 많은 유아·초등 저학년에게 맞다.',
    address: '서울특별시 용산구 한강대로23길 55 아이파크몰 리빙파크 6층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-champion-1250-gangdong',
    name: '챔피언1250 더리버몰 강동점',
    region: 'seoul',
    subRegion: '강동구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.etnews.com/20250410000061',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%B1%94%ED%94%BC%EC%96%B81250%20%EB%8D%94%EB%A6%AC%EB%B2%84%EB%AA%B0%20%EA%B0%95%EB%8F%99%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B0%95%EB%8F%99%EA%B5%AC%20%EA%B3%A0%EB%8D%95%EB%8F%99%20%EB%8D%94%EB%A6%AC%EB%B2%84%EB%AA%B0',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '더리버몰에 입점한 프리미엄 키즈 테마파크 후보. 순환형 짚라인과 어린이 방탈출형 프로그램 운영 신호가 있다.',
    address: '서울특별시 강동구 고덕동 더리버몰',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote: '보도자료 기반 후보라 발행 전 공식 예약 링크와 전화 확인이 필요하다.',
  },
  {
    id: 'seoul-ballbearpark-eunpyeong',
    name: '볼베어파크 롯데몰 은평점',
    region: 'seoul',
    subRegion: '은평구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'http://www.ballbearpark.com/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%B3%BC%EB%B2%A0%EC%96%B4%ED%8C%8C%ED%81%AC%20%EB%A1%AF%EB%8D%B0%EB%AA%B0%20%EC%9D%80%ED%8F%89%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%9D%80%ED%8F%89%EA%B5%AC%20%ED%86%B5%EC%9D%BC%EB%A1%9C%201050%20%EB%A1%AF%EB%8D%B0%EB%AA%B0%20%EC%9D%80%ED%8F%89%EC%A0%90%203%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '축구, 야구, 복싱, 볼챌린지 등 스포츠 체험을 결합한 어린이 스포츠 테마파크.',
    address: '서울특별시 은평구 통일로 1050 롯데몰 은평점 3층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'seoul-kids-plaza-hwagok',
    name: '서울 키즈플라자 / 서울형 키즈카페 시립 화곡점',
    region: 'seoul',
    subRegion: '강서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://news.seoul.go.kr/welfare/archives/575930',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%84%9C%EC%9A%B8%20%ED%82%A4%EC%A6%88%ED%94%8C%EB%9D%BC%EC%9E%90%20%2F%20%EC%84%9C%EC%9A%B8%ED%98%95%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20%EC%8B%9C%EB%A6%BD%20%ED%99%94%EA%B3%A1%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B0%95%EC%84%9C%EA%B5%AC%20%ED%99%94%EA%B3%A1%EB%8F%99%201172',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '서울 키즈플라자 1층에 있는 공공형 대형 실내 놀이터. 대형 미끄럼틀, 집라인, 클라이밍, 영아·유아 구역이 함께 있다.',
    address: '서울특별시 강서구 화곡동 1172',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
  },
  {
    id: 'seoul-monster-park-sindorim',
    name: '몬스터파크 신도림점',
    region: 'seoul',
    subRegion: '구로구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://monster-park.com/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%AA%AC%EC%8A%A4%ED%84%B0%ED%8C%8C%ED%81%AC%20%EC%8B%A0%EB%8F%84%EB%A6%BC%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B5%AC%EB%A1%9C%EA%B5%AC%20%EA%B2%BD%EC%9D%B8%EB%A1%9C%20661%20%ED%99%88%ED%94%8C%EB%9F%AC%EC%8A%A4%20%EC%8B%A0%EB%8F%84%EB%A6%BC%EC%A0%90%20%EC%A7%80%ED%95%981%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '시간 무제한형 실내 테마파크 콘셉트의 대형 키즈카페 후보. 브랜드 공식 페이지와 로컬 운영 신호를 함께 확인했다.',
    address: '서울특별시 구로구 경인로 661 홈플러스 신도림점 지하1층',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
    editorNote: '지점 공식 상세가 약해 발행 전 전화 확인이 필요하다.',
  },
  {
    id: 'seoul-kidzania-seoul',
    name: '키자니아 서울',
    region: 'seoul',
    subRegion: '송파구',
    category: 'experience',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.kidzania.co.kr/',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%82%A4%EC%9E%90%EB%8B%88%EC%95%84%20%EC%84%9C%EC%9A%B8%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%86%A1%ED%8C%8C%EA%B5%AC%20%EC%98%AC%EB%A6%BC%ED%94%BD%EB%A1%9C%20240',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '아이들이 도시 속 직업을 체험하는 실내 직업체험 테마파크. 키즈카페보다는 체험형 테마시설에 가깝지만, 비 오는 날 장시간 머무르기 좋다.',
    address: '서울특별시 송파구 올림픽로 240',
    priceInfo: '유료 / 반일권·종일권 등 공식 예매 기준 변동',
    rainFriendly: true,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote:
      '직업체험형 대체 후보. 이용권, 회차, 연령 기준은 공식 예매 화면에서 최종 확인해야 한다.',
  },
  {
    id: 'seoul-pororo-park-yeongdeungpo',
    name: '뽀로로파크 영등포점',
    region: 'seoul',
    subRegion: '영등포구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.pororopark.com/information/serviceHours.php',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%BD%80%EB%A1%9C%EB%A1%9C%ED%8C%8C%ED%81%AC%20%EC%98%81%EB%93%B1%ED%8F%AC%EC%A0%90%20%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC%20%EC%98%81%EC%A4%91%EB%A1%9C%2015',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '뽀로로 캐릭터 세계관을 기반으로 한 캐릭터형 키즈파크. 미취학 아이와 실내에서 오래 머물기 좋은 테마형 키즈카페 후보다.',
    address: '서울특별시 영등포구 영중로 15',
    priceInfo: '유료 / 지점·시즌별 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 이용시간 페이지에서 지점 운영 여부를 확인했다. 요금과 주차 지원은 발행 전 최신 예매 화면으로 재확인 필요.',
  },
  {
    id: 'national-children-museum',
    name: '국립어린이박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/site/child/home',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12207484',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '아이들이 직접 만지고 체험하는 어린이 전용 박물관. 0~12세 대상 다양한 체험 공간.',
    address: '서울 용산구 서빙고로 137 (국립중앙박물관 내)',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 2,000원, 성인 1,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '사전 예약 필수. 주말은 특히 빠르게 마감됨',
    thumbnailImage: '/images/places/national-children-museum.webp',
  },
  {
    id: 'national-folk-museum',
    name: '국립민속박물관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.nfm.go.kr/kids/nfmkid/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620599',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '경복궁 내에 위치한 국립 민속박물관. 어린이박물관은 무료 예약제로 운영돼 저연령 아이와 함께 들르기 좋다.',
    address: '서울 종로구 삼청로 37',
    operatingHours: '09:00-18:00 / 어린이박물관 09:30-16:50',
    priceInfo: '본관 무료 / 어린이박물관 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '어린이박물관은 1일 1회 온라인 예약제로 운영된다. 경복궁 동선과 함께 묶기 좋다.',
    thumbnailImage: '/images/places/national-folk-museum.webp',
  },
  {
    id: 'national-science-museum-gwacheon',
    name: '국립과천과학관',
    region: 'seoul',
    subRegion: '관악구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.sciencecenter.go.kr/scipia/display/mainBuilding/kidsPlayground',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12965666',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '과학 체험과 천문 관측이 가능한 국립 과학관. 유아체험관은 사전 예약으로 운영돼 미취학 아이와 함께 가기 좋다.',
    address: '경기 과천시 상하벌로 110',
    operatingHours: '09:30-17:30 (월요일 휴관, 유아체험관 회차 운영)',
    priceInfo: '상설전시 유료 / 유아체험관 미취학아동 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'public',
    editorNote:
      '유아체험관은 사전 예약 후 이용하는 편이 안전하다. 과천 위치지만 서울 생활권 나들이로 묶기 쉽다.',
    thumbnailImage: '/images/places/national-science-museum-gwacheon.webp',
  },
  {
    id: 'seodaemun-nature-history-museum',
    name: '서대문자연사박물관',
    region: 'seoul',
    subRegion: '서대문구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://namu.sdm.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620547',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '공룡 화석과 자연사 표본이 풍부한 구립 박물관. 아이들이 좋아하는 공룡 전시 상설 운영.',
    address: '서울 서대문구 연세로5나길 45',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 700원, 청소년 1,000원, 성인 3,000원',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '공룡을 좋아하는 아이들에게 강력 추천',
    thumbnailImage: '/images/places/seodaemun-nature-history-museum.webp',
  },
  {
    id: 'seoul-botanic-park',
    name: '서울식물원',
    region: 'seoul',
    subRegion: '강서구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://botanicpark.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1932878505',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '온실과 야외 정원이 함께 있는 도시형 식물원. 아이들이 자연을 가까이 접할 수 있는 공간.',
    address: '서울 강서구 마곡동로 161',
    operatingHours: '09:30-18:00 (월요일 휴관, 계절별 연장)',
    priceInfo: '어린이 1,000원, 성인 5,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '온실이 있어 우천에도 가능. 봄·가을 시즌 추천',
    thumbnailImage: '/images/places/seoul-botanic-park.webp',
  },
  {
    id: 'seoul-children-grand-park',
    name: '서울어린이대공원',
    region: 'seoul',
    subRegion: '광진구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.sisul.or.kr/open_content/childrenpark/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11796387',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '동물원, 식물원, 놀이공원이 함께 있는 서울 대표 어린이 공원. 무료 입장.',
    address: '서울 광진구 능동로 216',
    operatingHours: '05:00-22:00 (연중무휴, 일부 시설 별도 운영)',
    priceInfo: '공원 무료, 놀이 기구 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 180,
    operatorType: 'public',
    editorNote: '무료 공연과 계절 행사가 자주 열림',
    thumbnailImage: '/images/places/seoul-children-grand-park.webp',
  },
  {
    id: 'seoul-kids-book-museum',
    name: '서울특별시교육청 어린이도서관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://childlib.sen.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11591190',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '어린이를 위한 전용 공공 도서관. 다양한 독서 프로그램과 공간 운영.',
    address: '서울 종로구 사직로9길 7 (사직동 1-28)',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'seoul-national-museum-of-korea',
    name: '국립중앙박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/CHILD/main/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620570',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '국내 최대 규모의 국립박물관. 어린이박물관은 무료 예약제로 운영돼 체험형 관람 동선을 짜기 좋다.',
    address: '서울 용산구 서빙고로 137',
    operatingHours:
      '10:00-18:00 (수·토 21:00까지, 월요일 휴관) / 어린이박물관 09:30-17:20',
    priceInfo: '상설전시 무료 / 어린이박물관 무료 / 특별전 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '어린이박물관은 온라인 관람예약 후 이용하는 편이 안전하다.',
    thumbnailImage: '/images/places/seoul-national-museum-of-korea.webp',
  },
  {
    id: 'seoul-nature-ecology-center',
    name: '서울시립과학관',
    region: 'seoul',
    subRegion: '노원구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://science.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/515824798',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '서울시립과학관은 체험과 교육 중심의 과학 박물관. 야외 공원도 함께 이용 가능.',
    address: '서울 노원구 한글비석로 160',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 1,000원, 청소년 2,000원, 성인 3,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-nature-ecology-center.webp',
  },
  {
    id: 'seoul-olympic-park-sports',
    name: '올림픽공원',
    region: 'seoul',
    subRegion: '송파구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.kspo.or.kr/kspo/main/main.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12268494',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '넓은 잔디밭과 산책로가 있는 서울 대표 공원. 계절별 꽃 축제와 야외 체험 프로그램 운영.',
    address: '서울 송파구 올림픽로 424',
    operatingHours: '05:00-22:00 (연중무휴)',
    priceInfo: '공원 입장 무료, 일부 시설 유료',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-olympic-park-sports.webp',
  },
  {
    id: 'seoul-toy-library-mapo',
    name: '마포구 장난감도서관',
    region: 'seoul',
    subRegion: '마포구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.mapo.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13332819',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'semi_verified',
    description: '영유아 대상 장난감 대여 및 놀이 공간. 구민 무료 이용 가능.',
    address: '서울 마포구 마포대로 196',
    operatingHours: '09:00-18:00 (주말·공휴일 휴관)',
    priceInfo: '무료 (회원 등록 필요)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '각 구마다 장난감도서관이 다름. 거주지 확인 권장',
  },
  {
    id: 'seoul-sangsangnara',
    name: '서울상상나라',
    region: 'seoul',
    subRegion: '광진구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://seoulchildrensmuseum.org/index.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/31949741',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '놀이와 전시를 함께 엮은 서울 대표 어린이 체험형 박물관. 어린이대공원 실내 동선과 묶어 하루 코스를 짜기 좋다.',
    address: '서울특별시 광진구 능동로 216',
    operatingHours: '10:00-18:00',
    priceInfo: '36개월 이상 4,000원 / 36개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '온라인 예약제로 운영된다. 어린이대공원 주차장과 함께 이용하는 흐름이 편하다.',
  },
  {
    id: 'national-children-science-center',
    name: '국립어린이과학관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.csc.go.kr/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11796217',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '상설전시관을 무료로 이용할 수 있는 어린이 과학관. 창경궁 권역 실내 체험 코스로 묶기 좋다.',
    address: '서울 종로구 창경궁로 215',
    operatingHours: '09:30-17:30 (월요일 휴관)',
    priceInfo: '상설전시관 무료 / 일부 특별 프로그램 별도 운영',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '연나이 4세 이상 중심이다. 단체와 일부 프로그램은 사전 예약 여부를 먼저 확인하는 편이 안전하다.',
  },
  {
    id: 'seoul-baekje-childrens-museum',
    name: '서울백제어린이박물관',
    region: 'seoul',
    subRegion: '송파구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://baekjemuseum.seoul.go.kr/dreamvillage/board/notice/index.jsp?boardid=SDM0401000000&cpage=1&mmode=content&mpid=SDM0401000000&pg=1&pid=23111&skin=notice',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620616',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '올림픽공원 안에서 백제 역사를 어린이 눈높이 체험으로 풀어낸 박물관. 공원 산책과 실내 전시를 함께 묶기 좋다.',
    address: '서울특별시 송파구 올림픽로 424',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '상설 전시 무료 / 교육 프로그램 별도 예약 운영',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 관람은 현장 방문이 가능하고 일부 교육 프로그램은 서울시 공공서비스 예약으로 운영된다.',
  },
  {
    id: 'dooly-museum',
    name: '둘리뮤지엄',
    region: 'seoul',
    subRegion: '도봉구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.doolymuseum.or.kr/html/sub04/sub04_0405.php',
    naverMapUrl: 'https://map.naver.com/p/entry/place/32333709',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '둘리 세계관을 따라 전시와 체험을 즐기는 캐릭터 박물관. 미로정원과 드림스테이지까지 함께 둘러보기 좋다.',
    address: '서울특별시 도봉구 시루봉로1길 6',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '평일 4,000원 / 주말·공휴일 5,000원 / 24개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '무료 주차가 가능하지만 주말과 공휴일에는 주차 공간이 매우 협소하다.',
  },
  {
    id: 'seoul-public-kids-cafe-1',
    name: '서울형 키즈카페 시립 1호점',
    region: 'seoul',
    subRegion: '동작구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=DJ230901&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1983885754',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '서울가족플라자 안에서 회차제로 운영하는 공공 키즈카페. 동작권 실내 놀이 동선으로 묶기 좋다.',
    address: '서울특별시 동작구 노량진로 10 서울가족플라자 지하2층',
    priceInfo: '이용료·감면은 지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 4~10세 중심 이용 안내와 예약 버튼이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-ttukseom-jabeolle',
    name: '서울형 키즈카페 시립 뚝섬자벌레점',
    region: 'seoul',
    subRegion: '광진구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=GJ240401&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1163741876',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '한강 생활권에서 이용하기 좋은 공공 키즈카페. 영유아 중심 회차제로 운영돼 비 오는 날 실내 대안 동선으로 쓰기 좋다.',
    address: '서울특별시 광진구 강변북로 2202 2층 꿈틀나루',
    priceInfo: '회차형 예약 / 상세 요금은 지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '네이버 지도에는 서울형키즈카페 시립뚝섬자벌레점으로 표기된다.',
  },
  {
    id: 'seoul-public-kids-cafe-yangjae1',
    name: '서울형 키즈카페 서초구 양재1동점(서리풀노리학교 양재1동점)',
    region: 'seoul',
    subRegion: '서초구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbs.do?q_bbsCode=1028&q_bbscttSn=20251001180055700&q_fcltyId=SC231201',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1994004504',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '양재 생활권에서 이용하기 좋은 공공 키즈카페. 영유아 중심 회차형 운영으로 가까운 실내 육아 동선에 넣기 쉽다.',
    address: '서울특별시 서초구 양재천로 125-10 양재공영주차빌딩 2층',
    priceInfo: '회차형 예약 / 프로그램 공지형 운영',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '네이버 지도에는 서리풀노리학교 양재1동점으로 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-mokdong',
    name: '서울형 키즈카페 시립 목동점',
    region: 'seoul',
    subRegion: '양천구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=YC231201&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1476657870',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '양천 거점형 키움센터 안에서 회차제로 운영하는 공공 키즈카페. 안양천 생활권 실내 놀이 후보로 쓰기 좋다.',
    address: '서울특별시 양천구 안양천로 1131 지식산업센터 2층',
    priceInfo: '회차제 운영 / 상세 요금은 지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 3~12세 이용 안내와 예약 버튼이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-boramae',
    name: '서울형 키즈카페 시립 보라매공원점',
    region: 'seoul',
    subRegion: '동작구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=DJ250901&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/2093934615',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '보라매공원 인근에서 회차제로 운영하는 공공 키즈카페. 공원 산책과 실내 놀이를 묶기 좋은 도심형 거점이다.',
    address: '서울특별시 동작구 여의대방로20길 33 1층',
    priceInfo: '아동 1인 5,000원',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 3~9세 이용 연령과 보호자 동반 규칙이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-jayang4',
    name: '서울형 키즈카페 자양4동 2호점(꾸미팡팡 놀이터)',
    region: 'seoul',
    subRegion: '광진구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbs.do?q_bbsCode=1028&q_bbscttSn=20250923164636911&q_fcltyId=GJ240903',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1410258166',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '건대입구역 생활권에서 이용하기 좋은 공공 키즈카페. 공지형 운영으로 회차와 휴관일을 보고 움직이는 편이 안전하다.',
    address: '서울특별시 광진구 능동로 87 3층',
    priceInfo: '지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 공지 페이지에 운영일, 휴관일, 예약 신청 동선이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-dapsimni1',
    name: '서울형 키즈카페 답십리1동점',
    region: 'seoul',
    subRegion: '동대문구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbs.do?q_bbsCode=1028&q_bbscttSn=20251111105030310&q_fcltyId=DM250103',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1250250207',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '아파트 커뮤니티센터 안에서 운영하는 생활권형 공공 키즈카페. 동대문구 동네 육아 동선에 넣기 쉽다.',
    address: '서울특별시 동대문구 답십리로 130 309동 커뮤니티센터 내',
    priceInfo: '지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 공지 페이지에 운영일, 휴관일, 예약 신청이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-sindorim',
    name: '서울형 키즈카페 신도림동점',
    region: 'seoul',
    subRegion: '구로구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbsList.do?q_bbsCode=1028&q_fcltyId=GR250505&q_gubun=each',
    naverMapUrl: 'https://map.naver.com/p/entry/place/2144489674',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '신도림역 바로 옆에서 운영하는 역세권형 공공 키즈카페. 비 오는 날 짧게 들르기 좋은 실내 놀이 거점이다.',
    address: '서울특별시 구로구 경인로 688 신도림역 지상 2층',
    priceInfo: '프로그램·지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 페이지에 최근 프로그램과 휴무 공지가 함께 노출된다.',
  },
] satisfies PlaceSource[];
