import type { PlaceSource } from '../../../types/place-source.ts';

export const SEOUL_PLACES = [
  {
    id: 'national-children-museum',
    name: '국립어린이박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/site/child/home',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12207484',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '아이들이 직접 만지고 체험하는 어린이 전용 박물관. 0~12세 대상 다양한 체험 공간.',
    address: '서울 용산구 서빙고로 137 (국립중앙박물관 내)',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 2,000원, 성인 1,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '사전 예약 필수. 주말은 특히 빠르게 마감됨',
    thumbnailImage: '/images/places/national-children-museum.webp',
  },
  {
    id: 'national-folk-museum',
    name: '국립민속박물관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.nfm.go.kr/kids/nfmkid/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620599',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '경복궁 내에 위치한 국립 민속박물관. 어린이박물관은 무료 예약제로 운영돼 저연령 아이와 함께 들르기 좋다.',
    address: '서울 종로구 삼청로 37',
    operatingHours: '09:00-18:00 / 어린이박물관 09:30-16:50',
    priceInfo: '본관 무료 / 어린이박물관 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '어린이박물관은 1일 1회 온라인 예약제로 운영된다. 경복궁 동선과 함께 묶기 좋다.',
    thumbnailImage: '/images/places/national-folk-museum.webp',
  },
  {
    id: 'national-science-museum-gwacheon',
    name: '국립과천과학관',
    region: 'seoul',
    subRegion: '관악구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.sciencecenter.go.kr/scipia/display/mainBuilding/kidsPlayground',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12965666',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '과학 체험과 천문 관측이 가능한 국립 과학관. 유아체험관은 사전 예약으로 운영돼 미취학 아이와 함께 가기 좋다.',
    address: '경기 과천시 상하벌로 110',
    operatingHours: '09:30-17:30 (월요일 휴관, 유아체험관 회차 운영)',
    priceInfo: '상설전시 유료 / 유아체험관 미취학아동 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'public',
    editorNote: '유아체험관은 사전 예약 후 이용하는 편이 안전하다. 과천 위치지만 서울 생활권 나들이로 묶기 쉽다.',
    thumbnailImage: '/images/places/national-science-museum-gwacheon.webp',
  },
  {
    id: 'seodaemun-nature-history-museum',
    name: '서대문자연사박물관',
    region: 'seoul',
    subRegion: '서대문구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://namu.sdm.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620547',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '공룡 화석과 자연사 표본이 풍부한 구립 박물관. 아이들이 좋아하는 공룡 전시 상설 운영.',
    address: '서울 서대문구 연세로5나길 45',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 700원, 청소년 1,000원, 성인 3,000원',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '공룡을 좋아하는 아이들에게 강력 추천',
    thumbnailImage: '/images/places/seodaemun-nature-history-museum.webp',
  },
  {
    id: 'seoul-botanic-park',
    name: '서울식물원',
    region: 'seoul',
    subRegion: '강서구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://botanicpark.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1932878505',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '온실과 야외 정원이 함께 있는 도시형 식물원. 아이들이 자연을 가까이 접할 수 있는 공간.',
    address: '서울 강서구 마곡동로 161',
    operatingHours: '09:30-18:00 (월요일 휴관, 계절별 연장)',
    priceInfo: '어린이 1,000원, 성인 5,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '온실이 있어 우천에도 가능. 봄·가을 시즌 추천',
    thumbnailImage: '/images/places/seoul-botanic-park.webp',
  },
  {
    id: 'seoul-children-grand-park',
    name: '서울어린이대공원',
    region: 'seoul',
    subRegion: '광진구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.sisul.or.kr/open_content/childrenpark/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11796387',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '동물원, 식물원, 놀이공원이 함께 있는 서울 대표 어린이 공원. 무료 입장.',
    address: '서울 광진구 능동로 216',
    operatingHours: '05:00-22:00 (연중무휴, 일부 시설 별도 운영)',
    priceInfo: '공원 무료, 놀이 기구 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 180,
    operatorType: 'public',
    editorNote: '무료 공연과 계절 행사가 자주 열림',
    thumbnailImage: '/images/places/seoul-children-grand-park.webp',
  },
  {
    id: 'seoul-kids-book-museum',
    name: '서울특별시교육청 어린이도서관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://childlib.sen.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11591190',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '어린이를 위한 전용 공공 도서관. 다양한 독서 프로그램과 공간 운영.',
    address: '서울 종로구 사직로9길 7 (사직동 1-28)',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'seoul-national-museum-of-korea',
    name: '국립중앙박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/CHILD/main/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620570',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '국내 최대 규모의 국립박물관. 어린이박물관은 무료 예약제로 운영돼 체험형 관람 동선을 짜기 좋다.',
    address: '서울 용산구 서빙고로 137',
    operatingHours: '10:00-18:00 (수·토 21:00까지, 월요일 휴관) / 어린이박물관 09:30-17:20',
    priceInfo: '상설전시 무료 / 어린이박물관 무료 / 특별전 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '어린이박물관은 온라인 관람예약 후 이용하는 편이 안전하다.',
    thumbnailImage: '/images/places/seoul-national-museum-of-korea.webp',
  },
  {
    id: 'seoul-nature-ecology-center',
    name: '서울시립과학관',
    region: 'seoul',
    subRegion: '노원구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://science.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/515824798',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '서울시립과학관은 체험과 교육 중심의 과학 박물관. 야외 공원도 함께 이용 가능.',
    address: '서울 노원구 한글비석로 160',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 1,000원, 청소년 2,000원, 성인 3,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-nature-ecology-center.webp',
  },
  {
    id: 'seoul-olympic-park-sports',
    name: '올림픽공원',
    region: 'seoul',
    subRegion: '송파구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.kspo.or.kr/kspo/main/main.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12268494',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '넓은 잔디밭과 산책로가 있는 서울 대표 공원. 계절별 꽃 축제와 야외 체험 프로그램 운영.',
    address: '서울 송파구 올림픽로 424',
    operatingHours: '05:00-22:00 (연중무휴)',
    priceInfo: '공원 입장 무료, 일부 시설 유료',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-olympic-park-sports.webp',
  },
  {
    id: 'seoul-toy-library-mapo',
    name: '마포구 장난감도서관',
    region: 'seoul',
    subRegion: '마포구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.mapo.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13332819',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'semi_verified',
    description: '영유아 대상 장난감 대여 및 놀이 공간. 구민 무료 이용 가능.',
    address: '서울 마포구 마포대로 196',
    operatingHours: '09:00-18:00 (주말·공휴일 휴관)',
    priceInfo: '무료 (회원 등록 필요)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '각 구마다 장난감도서관이 다름. 거주지 확인 권장',
  },
] satisfies PlaceSource[];
