import type { PlaceSource } from '../../../types/place-source.ts';

export const SEOUL_PLACES = [
  {
    id: 'national-children-museum',
    name: '국립어린이박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/site/child/home',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12207484',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '아이들이 직접 만지고 체험하는 어린이 전용 박물관. 0~12세 대상 다양한 체험 공간.',
    address: '서울 용산구 서빙고로 137 (국립중앙박물관 내)',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 2,000원, 성인 1,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '사전 예약 필수. 주말은 특히 빠르게 마감됨',
    thumbnailImage: '/images/places/national-children-museum.webp',
  },
  {
    id: 'national-folk-museum',
    name: '국립민속박물관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.nfm.go.kr/kids/nfmkid/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620599',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '경복궁 내에 위치한 국립 민속박물관. 어린이박물관은 무료 예약제로 운영돼 저연령 아이와 함께 들르기 좋다.',
    address: '서울 종로구 삼청로 37',
    operatingHours: '09:00-18:00 / 어린이박물관 09:30-16:50',
    priceInfo: '본관 무료 / 어린이박물관 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '어린이박물관은 1일 1회 온라인 예약제로 운영된다. 경복궁 동선과 함께 묶기 좋다.',
    thumbnailImage: '/images/places/national-folk-museum.webp',
  },
  {
    id: 'national-science-museum-gwacheon',
    name: '국립과천과학관',
    region: 'seoul',
    subRegion: '관악구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.sciencecenter.go.kr/scipia/display/mainBuilding/kidsPlayground',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12965666',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '과학 체험과 천문 관측이 가능한 국립 과학관. 유아체험관은 사전 예약으로 운영돼 미취학 아이와 함께 가기 좋다.',
    address: '경기 과천시 상하벌로 110',
    operatingHours: '09:30-17:30 (월요일 휴관, 유아체험관 회차 운영)',
    priceInfo: '상설전시 유료 / 유아체험관 미취학아동 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'public',
    editorNote:
      '유아체험관은 사전 예약 후 이용하는 편이 안전하다. 과천 위치지만 서울 생활권 나들이로 묶기 쉽다.',
    thumbnailImage: '/images/places/national-science-museum-gwacheon.webp',
  },
  {
    id: 'seodaemun-nature-history-museum',
    name: '서대문자연사박물관',
    region: 'seoul',
    subRegion: '서대문구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://namu.sdm.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620547',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '공룡 화석과 자연사 표본이 풍부한 구립 박물관. 아이들이 좋아하는 공룡 전시 상설 운영.',
    address: '서울 서대문구 연세로5나길 45',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 700원, 청소년 1,000원, 성인 3,000원',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '공룡을 좋아하는 아이들에게 강력 추천',
    thumbnailImage: '/images/places/seodaemun-nature-history-museum.webp',
  },
  {
    id: 'seoul-botanic-park',
    name: '서울식물원',
    region: 'seoul',
    subRegion: '강서구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://botanicpark.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1932878505',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '온실과 야외 정원이 함께 있는 도시형 식물원. 아이들이 자연을 가까이 접할 수 있는 공간.',
    address: '서울 강서구 마곡동로 161',
    operatingHours: '09:30-18:00 (월요일 휴관, 계절별 연장)',
    priceInfo: '어린이 1,000원, 성인 5,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '온실이 있어 우천에도 가능. 봄·가을 시즌 추천',
    thumbnailImage: '/images/places/seoul-botanic-park.webp',
  },
  {
    id: 'seoul-children-grand-park',
    name: '서울어린이대공원',
    region: 'seoul',
    subRegion: '광진구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.sisul.or.kr/open_content/childrenpark/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11796387',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '동물원, 식물원, 놀이공원이 함께 있는 서울 대표 어린이 공원. 무료 입장.',
    address: '서울 광진구 능동로 216',
    operatingHours: '05:00-22:00 (연중무휴, 일부 시설 별도 운영)',
    priceInfo: '공원 무료, 놀이 기구 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 180,
    operatorType: 'public',
    editorNote: '무료 공연과 계절 행사가 자주 열림',
    thumbnailImage: '/images/places/seoul-children-grand-park.webp',
  },
  {
    id: 'seoul-kids-book-museum',
    name: '서울특별시교육청 어린이도서관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://childlib.sen.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11591190',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '어린이를 위한 전용 공공 도서관. 다양한 독서 프로그램과 공간 운영.',
    address: '서울 종로구 사직로9길 7 (사직동 1-28)',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'seoul-national-museum-of-korea',
    name: '국립중앙박물관',
    region: 'seoul',
    subRegion: '용산구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.museum.go.kr/CHILD/main/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620570',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '국내 최대 규모의 국립박물관. 어린이박물관은 무료 예약제로 운영돼 체험형 관람 동선을 짜기 좋다.',
    address: '서울 용산구 서빙고로 137',
    operatingHours:
      '10:00-18:00 (수·토 21:00까지, 월요일 휴관) / 어린이박물관 09:30-17:20',
    priceInfo: '상설전시 무료 / 어린이박물관 무료 / 특별전 유료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '어린이박물관은 온라인 관람예약 후 이용하는 편이 안전하다.',
    thumbnailImage: '/images/places/seoul-national-museum-of-korea.webp',
  },
  {
    id: 'seoul-nature-ecology-center',
    name: '서울시립과학관',
    region: 'seoul',
    subRegion: '노원구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://science.seoul.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/515824798',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '서울시립과학관은 체험과 교육 중심의 과학 박물관. 야외 공원도 함께 이용 가능.',
    address: '서울 노원구 한글비석로 160',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '어린이 1,000원, 청소년 2,000원, 성인 3,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-nature-ecology-center.webp',
  },
  {
    id: 'seoul-olympic-park-sports',
    name: '올림픽공원',
    region: 'seoul',
    subRegion: '송파구',
    category: 'park',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.kspo.or.kr/kspo/main/main.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12268494',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '넓은 잔디밭과 산책로가 있는 서울 대표 공원. 계절별 꽃 축제와 야외 체험 프로그램 운영.',
    address: '서울 송파구 올림픽로 424',
    operatingHours: '05:00-22:00 (연중무휴)',
    priceInfo: '공원 입장 무료, 일부 시설 유료',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 120,
    operatorType: 'public',
    thumbnailImage: '/images/places/seoul-olympic-park-sports.webp',
  },
  {
    id: 'seoul-toy-library-mapo',
    name: '마포구 장난감도서관',
    region: 'seoul',
    subRegion: '마포구',
    category: 'library',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.mapo.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13332819',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'semi_verified',
    description: '영유아 대상 장난감 대여 및 놀이 공간. 구민 무료 이용 가능.',
    address: '서울 마포구 마포대로 196',
    operatingHours: '09:00-18:00 (주말·공휴일 휴관)',
    priceInfo: '무료 (회원 등록 필요)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '각 구마다 장난감도서관이 다름. 거주지 확인 권장',
  },
  {
    id: 'seoul-sangsangnara',
    name: '서울상상나라',
    region: 'seoul',
    subRegion: '광진구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://seoulchildrensmuseum.org/index.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/31949741',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '놀이와 전시를 함께 엮은 서울 대표 어린이 체험형 박물관. 어린이대공원 실내 동선과 묶어 하루 코스를 짜기 좋다.',
    address: '서울특별시 광진구 능동로 216',
    operatingHours: '10:00-18:00',
    priceInfo: '36개월 이상 4,000원 / 36개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '온라인 예약제로 운영된다. 어린이대공원 주차장과 함께 이용하는 흐름이 편하다.',
  },
  {
    id: 'national-children-science-center',
    name: '국립어린이과학관',
    region: 'seoul',
    subRegion: '종로구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.csc.go.kr/index.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11796217',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '상설전시관을 무료로 이용할 수 있는 어린이 과학관. 창경궁 권역 실내 체험 코스로 묶기 좋다.',
    address: '서울 종로구 창경궁로 215',
    operatingHours: '09:30-17:30 (월요일 휴관)',
    priceInfo: '상설전시관 무료 / 일부 특별 프로그램 별도 운영',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '연나이 4세 이상 중심이다. 단체와 일부 프로그램은 사전 예약 여부를 먼저 확인하는 편이 안전하다.',
  },
  {
    id: 'seoul-baekje-childrens-museum',
    name: '서울백제어린이박물관',
    region: 'seoul',
    subRegion: '송파구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://baekjemuseum.seoul.go.kr/dreamvillage/board/notice/index.jsp?boardid=SDM0401000000&cpage=1&mmode=content&mpid=SDM0401000000&pg=1&pid=23111&skin=notice',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620616',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '올림픽공원 안에서 백제 역사를 어린이 눈높이 체험으로 풀어낸 박물관. 공원 산책과 실내 전시를 함께 묶기 좋다.',
    address: '서울특별시 송파구 올림픽로 424',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    priceInfo: '상설 전시 무료 / 교육 프로그램 별도 예약 운영',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 관람은 현장 방문이 가능하고 일부 교육 프로그램은 서울시 공공서비스 예약으로 운영된다.',
  },
  {
    id: 'dooly-museum',
    name: '둘리뮤지엄',
    region: 'seoul',
    subRegion: '도봉구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.doolymuseum.or.kr/html/sub04/sub04_0405.php',
    naverMapUrl: 'https://map.naver.com/p/entry/place/32333709',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '둘리 세계관을 따라 전시와 체험을 즐기는 캐릭터 박물관. 미로정원과 드림스테이지까지 함께 둘러보기 좋다.',
    address: '서울특별시 도봉구 시루봉로1길 6',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '평일 4,000원 / 주말·공휴일 5,000원 / 24개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '무료 주차가 가능하지만 주말과 공휴일에는 주차 공간이 매우 협소하다.',
  },
  {
    id: 'seoul-public-kids-cafe-1',
    name: '서울형 키즈카페 시립 1호점',
    region: 'seoul',
    subRegion: '동작구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=DJ230901&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1983885754',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '서울가족플라자 안에서 회차제로 운영하는 공공 키즈카페. 동작권 실내 놀이 동선으로 묶기 좋다.',
    address: '서울특별시 동작구 노량진로 10 서울가족플라자 지하2층',
    priceInfo: '이용료·감면은 지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 4~10세 중심 이용 안내와 예약 버튼이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-mokdong',
    name: '서울형 키즈카페 시립 목동점',
    region: 'seoul',
    subRegion: '양천구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=YC231201&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1476657870',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '양천 거점형 키움센터 안에서 회차제로 운영하는 공공 키즈카페. 안양천 생활권 실내 놀이 후보로 쓰기 좋다.',
    address: '서울특별시 양천구 안양천로 1131 지식산업센터 2층',
    priceInfo: '회차제 운영 / 상세 요금은 지점 안내 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 3~12세 이용 안내와 예약 버튼이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-boramae',
    name: '서울형 키즈카페 시립 보라매공원점',
    region: 'seoul',
    subRegion: '동작구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/kidsCafe/BD_selectKidsCafeView.do?q_fcltyId=DJ250901&q_fcltyStle=',
    naverMapUrl: 'https://map.naver.com/p/entry/place/2093934615',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '보라매공원 인근에서 회차제로 운영하는 공공 키즈카페. 공원 산책과 실내 놀이를 묶기 좋은 도심형 거점이다.',
    address: '서울특별시 동작구 여의대방로20길 33 1층',
    priceInfo: '아동 1인 5,000원',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 상세에 3~9세 이용 연령과 보호자 동반 규칙이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-jayang4',
    name: '서울형 키즈카페 자양4동 2호점(꾸미팡팡 놀이터)',
    region: 'seoul',
    subRegion: '광진구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbs.do?q_bbsCode=1028&q_bbscttSn=20250923164636911&q_fcltyId=GJ240903',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1410258166',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '건대입구역 생활권에서 이용하기 좋은 공공 키즈카페. 공지형 운영으로 회차와 휴관일을 보고 움직이는 편이 안전하다.',
    address: '서울특별시 광진구 능동로 87 3층',
    priceInfo: '지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 공지 페이지에 운영일, 휴관일, 예약 신청 동선이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-dapsimni1',
    name: '서울형 키즈카페 답십리1동점',
    region: 'seoul',
    subRegion: '동대문구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbs.do?q_bbsCode=1028&q_bbscttSn=20251111105030310&q_fcltyId=DM250103',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1250250207',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '아파트 커뮤니티센터 안에서 운영하는 생활권형 공공 키즈카페. 동대문구 동네 육아 동선에 넣기 쉽다.',
    address: '서울특별시 동대문구 답십리로 130 309동 커뮤니티센터 내',
    priceInfo: '지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 공지 페이지에 운영일, 휴관일, 예약 신청이 노출된다.',
  },
  {
    id: 'seoul-public-kids-cafe-sindorim',
    name: '서울형 키즈카페 신도림동점',
    region: 'seoul',
    subRegion: '구로구',
    category: 'public-play',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://umppa.seoul.go.kr/icare/user/bbs/BD_selectBbsList.do?q_bbsCode=1028&q_fcltyId=GR250505&q_gubun=each',
    naverMapUrl: 'https://map.naver.com/p/entry/place/2144489674',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '신도림역 바로 옆에서 운영하는 역세권형 공공 키즈카페. 비 오는 날 짧게 들르기 좋은 실내 놀이 거점이다.',
    address: '서울특별시 구로구 경인로 688 신도림역 지상 2층',
    priceInfo: '프로그램·지점 공지 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 페이지에 최근 프로그램과 휴무 공지가 함께 노출된다.',
  },
] satisfies PlaceSource[];
