import type { PlaceSource } from '../../../types/place-source.ts';

export const GYEONGGI_SOUTH_PLACES = [
  {
    id: 'ansan-astro-camp',
    name: '안산어린이천문대',
    region: 'gyeonggi-south',
    subRegion: '안산시',
    category: 'experience',
    ageBands: ['6-10y', 'all'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://cafe.naver.com/astroansan',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37458087',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '안산시에서 운영하는 공공 천문대. 낮 관람과 야간 별자리 관측 프로그램 운영.',
    address: '경기 안산시 상록구 반월로 399',
    operatingHours: '14:00-22:00 (월·화 휴관, 시즌별 변동)',
    priceInfo: '어린이 1,000원, 청소년 1,500원, 성인 2,000원',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '야간 관측 프로그램은 초등학생 이상 적합',
  },
  {
    id: 'everland',
    name: '에버랜드',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.everland.com/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11574457',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description: '국내 최대 테마파크. 어린이 전용 존과 동물원, 워터파크 포함.',
    address: '경기 용인시 처인구 포곡읍 에버랜드로 199',
    operatingHours: '10:00-21:00 (시즌별 변동)',
    priceInfo:
      '어린이 50,000원대, 성인 60,000원대 (자유이용권 기준, 변동 가능)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 480,
    operatorType: 'commercial',
    editorNote: '가격·운영시간은 시즌마다 바뀜. 공식 홈페이지 사전 확인 필수',
    thumbnailImage: '/images/places/everland.webp',
  },
  {
    id: 'gyeonggi-children-museum',
    name: '경기도어린이박물관',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://gcm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13172610',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '경기도가 운영하는 어린이 전용 체험 박물관. 영유아부터 초등학생까지 대상별 전시 공간.',
    address: '경기 용인시 기흥구 상갈로 6',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '어린이·성인 모두 4,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '사전 예약 필수. 주말 예약 빠르게 마감',
    thumbnailImage: '/images/places/gyeonggi-children-museum.webp',
  },
  {
    id: 'korea-folk-village',
    name: '한국민속촌',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'culture',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.koreanfolk.co.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620801',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '전통 한국 생활문화를 체험할 수 있는 야외 테마 공원. 계절별 전통 공연과 체험 운영.',
    address: '경기 용인시 기흥구 민속촌로 90',
    operatingHours: '09:30-18:00 (시즌별 변동)',
    priceInfo: '어린이 15,000원, 성인 25,000원 (변동 가능)',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote: '비포장 구간 있어 유모차 이동 어려움. 걷기 편한 신발 필수',
    thumbnailImage: '/images/places/korea-folk-village.webp',
  },
  {
    id: 'siheung-kids-cafe-sample',
    name: '시흥 키즈카페 (대형 복합형)',
    region: 'gyeonggi-south',
    subRegion: '시흥시',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'discovery',
    sourceUrl: 'https://map.naver.com/',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'needs_refresh',
    description:
      '시흥 소재 대형 키즈카페 대표 샘플. 실제 발행 전 공식 확인 필요.',
    address: '경기 시흥시 일대',
    priceInfo: '시간제 이용 (업체별 상이, 약 10,000~15,000원)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '이 항목은 discovery 상태로 공식 검증 전 발행 불가. 실제 운영 업체 직접 확인 필요',
  },
  {
    id: 'suwon-hwaseong-fortress',
    name: '수원화성',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'culture',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.swcf.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13491459',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '유네스코 세계문화유산 수원화성. 성곽 둘레길과 행궁 관람, 전통 무예 공연 포함.',
    address: '경기 수원시 팔달구 행궁로 11',
    operatingHours: '09:00-18:00 (연중무휴, 시즌별 변동)',
    priceInfo: '어린이 700원, 성인 1,500원',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 150,
    operatorType: 'public',
    editorNote:
      '성곽 둘레길은 유모차 이동 어려움. 화성행궁 실내 관람 위주 권장',
    thumbnailImage: '/images/places/suwon-hwaseong-fortress.webp',
  },
] satisfies PlaceSource[];
