import type { PlaceSource } from '../../../types/place-source.ts';

export const GYEONGGI_SOUTH_PLACES = [
  {
    id: 'gyeonggi-south-isarang-cityhall',
    name: '시청1·2호 아이사랑놀이터',
    region: 'gyeonggi-south',
    subRegion: '성남시 중원구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'http://sneducare.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%8B%9C%EC%B2%AD1%C2%B72%ED%98%B8%20%EC%95%84%EC%9D%B4%EC%82%AC%EB%9E%91%EB%86%80%EC%9D%B4%ED%84%B0%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%84%B1%EB%82%A8%EC%8B%9C%20%EC%A4%91%EC%9B%90%EA%B5%AC%20%EC%84%B1%EB%82%A8%EB%8C%80%EB%A1%9C%20997%20%EC%84%B1%EB%82%A8%EC%8B%9C%EC%B2%AD%209%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '성남시청 안에 있는 공공 아이사랑놀이터. 부모와 영유아가 함께 놀이하는 실내 공간이다.',
    address: '경기도 성남시 중원구 성남대로 997 성남시청 9층',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-south-ansan-ilovemom-cafe',
    name: '안산시 아이러브맘카페',
    region: 'gyeonggi-south',
    subRegion: '안산시 단원구',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'http://ilovemom.ansanbo6.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%95%88%EC%82%B0%EC%8B%9C%20%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%95%88%EC%82%B0%EC%8B%9C%20%EB%8B%A8%EC%9B%90%EA%B5%AC%20%EA%B4%91%EB%8D%952%EB%A1%9C%20249',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '안산 공공 아이러브맘카페. 영유아와 보호자가 함께 이용하는 생활권 실내 육아 공간이다.',
    address: '경기도 안산시 단원구 광덕2로 249',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-south-hwaseong-ilovemom-hyangnam1',
    name: '아이러브맘카페 향남1호점',
    region: 'gyeonggi-south',
    subRegion: '화성시 향남읍',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'http://hsicare.or.kr/imom',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%ED%96%A5%EB%82%A81%ED%98%B8%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%99%94%EC%84%B1%EC%8B%9C%20%ED%96%A5%EB%82%A8%EC%9D%8D%20%ED%96%89%EC%A0%95%EB%82%A8%EB%A1%9C%2099-16%20%ED%96%A5%EB%82%A8%ED%95%9C%EC%9A%B0%EB%AC%BC%EB%A7%88%EC%9D%84%206%EB%8B%A8%EC%A7%80%20%EA%B4%80%EB%A6%AC%EB%8F%99%203%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '화성 향남권 공공 아이러브맘카페. 영유아와 보호자가 짧게 머물기 좋은 실내 육아 거점이다.',
    address: '경기도 화성시 향남읍 행정남로 99-16 향남한우물마을 6단지 관리동 3층',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-south-hwaseong-ilovemom-bansong',
    name: '아이러브맘카페 반송점',
    region: 'gyeonggi-south',
    subRegion: '화성시 반송동',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'http://hsicare.or.kr/imom',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%EB%B0%98%EC%86%A1%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%99%94%EC%84%B1%EC%8B%9C%20%EB%8F%99%ED%83%84%EB%B0%98%EC%84%9D%EB%A1%9C%2031%203%EC%B8%B5',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '동탄 생활권 공공 아이러브맘카페. 부모와 영유아가 함께 이용하는 실내 놀이·쉼 공간이다.',
    address: '경기도 화성시 동탄반석로 31 3층',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-south-anyang-ilovemom-cafe',
    name: '안양시 아이러브맘카페',
    region: 'gyeonggi-south',
    subRegion: '안양시 만안구',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'http://aycteducare.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%95%88%EC%96%91%EC%8B%9C%20%EC%95%84%EC%9D%B4%EB%9F%AC%EB%B8%8C%EB%A7%98%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%95%88%EC%96%91%EC%8B%9C%20%EB%A7%8C%EC%95%88%EA%B5%AC%20%EC%95%88%EC%96%91%EB%A1%9C%20138%20%EB%B3%84%EA%B4%80',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '안양 중심권 공공 아이러브맘카페. 영유아와 보호자가 함께 머무는 생활권 실내 공간이다.',
    address: '경기도 안양시 만안구 안양로 138 별관',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
  },
  {
    id: 'gyeonggi-south-thegreem-yangpyeong',
    name: '더그림',
    region: 'gyeonggi-south',
    subRegion: '양평군',
    category: 'culture',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.thegreem.net/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%8D%94%EA%B7%B8%EB%A6%BC%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%96%91%ED%8F%89%EA%B5%B0%20%EC%98%A5%EC%B2%9C%EB%A9%B4%20%EC%82%AC%EB%82%98%EC%82%AC%EA%B8%B8%20175',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '정원, 유리온실, 자연 조망이 있는 가족 동반 카페. 소인 요금 체계가 공식 사이트에서 확인된다.',
    address: '경기도 양평군 옥천면 사나사길 175',
    rainFriendly: false,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-muisup-yeoju',
    name: '무이숲',
    region: 'gyeonggi-south',
    subRegion: '여주시',
    category: 'culture',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://purme.org/board/story/7131',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%AC%B4%EC%9D%B4%EC%88%B2%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%97%AC%EC%A3%BC%EC%8B%9C%20%EB%8F%84%EC%98%88%EB%A1%9C%20247',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'semi_verified',
    description:
      '470평 규모 문화공간형 베이커리 카페. 공식 오픈 안내와 예약 채널에서 가족 동반 신호가 확인된다.',
    address: '경기도 여주시 도예로 247',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ikea-gwangmyeong-swedish-cafe',
    name: 'IKEA 광명 스웨디시 카페',
    region: 'gyeonggi-south',
    subRegion: '광명시',
    category: 'culture',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ikea.com/kr/ko/stores/gwangmyeong/ikea-food-gm-pub2c354a9a/',
    naverMapUrl: 'https://map.naver.com/p/search/IKEA%20%EA%B4%91%EB%AA%85%20%EC%8A%A4%EC%9B%A8%EB%94%94%EC%8B%9C%20%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B4%91%EB%AA%85%EC%8B%9C%20%EC%9D%BC%EC%A7%81%EB%A1%9C%2017',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '영유아 이유식 무료와 어린이 놀이공간 신호가 있는 IKEA 광명점 가족형 카페·레스토랑 동선.',
    address: '경기도 광명시 일직로 17',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ikea-giheung-swedish-cafe',
    name: 'IKEA 기흥 스웨디시 카페',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'culture',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ikea.com/kr/ko/stores/giheung/ikea-food-gh-pub7ccd42b2/',
    naverMapUrl: 'https://map.naver.com/p/search/IKEA%20%EA%B8%B0%ED%9D%A5%20%EC%8A%A4%EC%9B%A8%EB%94%94%EC%8B%9C%20%EC%B9%B4%ED%8E%98%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%9A%A9%EC%9D%B8%EC%8B%9C%20%EA%B8%B0%ED%9D%A5%EA%B5%AC%20%EC%8B%A0%EA%B3%A0%EB%A7%A4%EB%A1%9C%2062',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '영유아 이유식 무료와 어린이 놀이공간 신호가 있는 IKEA 기흥점 가족형 카페·레스토랑 동선.',
    address: '경기도 용인시 기흥구 신고매로 62',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-aquafield-anseong-cafe-de-aqua',
    name: '아쿠아필드 안성 카페 드 아쿠아',
    region: 'gyeonggi-south',
    subRegion: '안성시',
    category: 'culture',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/anseong/entertainment/aquafield.do',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%95%84%EC%BF%A0%EC%95%84%ED%95%84%EB%93%9C%20%EC%95%88%EC%84%B1%20%EC%B9%B4%ED%8E%98%20%EB%93%9C%20%EC%95%84%EC%BF%A0%EC%95%84%20%EA%B2%BD%EA%B8%B0%20%EC%95%88%EC%84%B1%EC%8B%9C%20%EA%B3%B5%EB%8F%84%EC%9D%8D%20%EC%84%9C%EB%8F%99%EB%8C%80%EB%A1%9C%203930-39',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '피쉬뷰 카페, 루프탑, 패밀리홀, 키즈존을 결합한 스타필드 안성 가족형 복합 카페 공간.',
    address: '경기 안성시 공도읍 서동대로 3930-39',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ikea-gwangmyeong-smaland',
    name: 'IKEA Småland 광명점',
    region: 'gyeonggi-south',
    subRegion: '광명시',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ikea.com/kr/en/stores/gwangmyeong/ikea-smaland-pub65675972',
    naverMapUrl: 'https://map.naver.com/p/search/IKEA%20Sm%C3%A5land%20%EA%B4%91%EB%AA%85%EC%A0%90%20IKEA%20Gwangmyeong%2C%2017%20Iljik-ro%2C%20Gwangmyeong-si',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      'IKEA 광명점 내 무료 키즈 플레이어리어. 배변 독립과 키 제한이 있어 조건 확인이 필요하다.',
    address: 'IKEA Gwangmyeong, 17 Iljik-ro, Gwangmyeong-si',
    priceInfo: '무료 / 현장 등록',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ikea-giheung-smaland',
    name: 'IKEA Småland 기흥점',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ikea.com/kr/en/stores/giheung/ikea-smaland-pub7156b0b1/',
    naverMapUrl: 'https://map.naver.com/p/search/IKEA%20Sm%C3%A5land%20%EA%B8%B0%ED%9D%A5%EC%A0%90%20IKEA%20Giheung%2C%2062%20Singomae-ro%2C%20Giheung-gu%2C%20Yongin-si',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      'IKEA 기흥점 내 무료 키즈 플레이어리어. 키 제한과 배변 독립 조건이 있어 방문 전 확인이 필요하다.',
    address: 'IKEA Giheung, 62 Singomae-ro, Giheung-gu, Yongin-si',
    priceInfo: '무료 / 현장 등록',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-starfied-bucheon-byeolmadang-kids',
    name: '별마당 키즈 스타필드 시티 부천',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'library',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/bucheon/entertainment/libraryKids.do',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%B3%84%EB%A7%88%EB%8B%B9%20%ED%82%A4%EC%A6%88%20%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%20%EC%8B%9C%ED%8B%B0%20%EB%B6%80%EC%B2%9C%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EB%B6%80%EC%B2%9C%EC%8B%9C%20%EC%98%A5%EA%B8%B8%EB%A1%9C%201',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '스타필드 시티 부천의 아동 특화 도서관형 실내 공간. 쇼핑몰 동선에서 짧게 머물기 좋다.',
    address: '경기도 부천시 옥길로 1',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-monello-siheung-neunggok',
    name: '모넬로 키즈카페 시흥능곡역점',
    region: 'gyeonggi-south',
    subRegion: '시흥시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EB%AA%A8%EB%84%AC%EB%A1%9C-%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98-%EC%8B%9C%ED%9D%A5%EB%8A%A5%EA%B3%A1%EC%97%AD%EC%A0%90-1722126/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%AA%A8%EB%84%AC%EB%A1%9C%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20%EC%8B%9C%ED%9D%A5%EB%8A%A5%EA%B3%A1%EC%97%AD%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%8B%9C%ED%9D%A5%EC%8B%9C%20%EB%8A%A5%EA%B3%A1%EB%B2%88%EC%98%81%EA%B8%B8%2030',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '시흥 능곡역권 로컬 키즈카페. 당근 업체 프로필과 네이버 플레이스 운영 신호가 교차 확인된다.',
    address: '경기도 시흥시 능곡번영길 30',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-gguljam-kidsroom-ansan',
    name: '꿀잼키즈룸 안산중앙점',
    region: 'gyeonggi-south',
    subRegion: '안산시 단원구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EA%BF%80%EC%9E%BC%ED%82%A4%EC%A6%88%EB%A3%B8-%EC%95%88%EC%82%B0%EC%A4%91%EC%95%99%EC%A0%90-bk8bgr74g2oo/',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%BF%80%EC%9E%BC%ED%82%A4%EC%A6%88%EB%A3%B8%20%EC%95%88%EC%82%B0%EC%A4%91%EC%95%99%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%95%88%EC%82%B0%EC%8B%9C%20%EB%8B%A8%EC%9B%90%EA%B5%AC%20%EB%8B%B9%EA%B3%A1%EB%A1%9C%2027',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '안산 중앙권 프라이빗 무인 키즈룸. 예약제 안내와 네이버 플레이스 링크가 확인된다.',
    address: '경기도 안산시 단원구 당곡로 27',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-little-pongdang-yongin',
    name: '리틀퐁당',
    region: 'gyeonggi-south',
    subRegion: '용인시 기흥구',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%EB%A6%AC%ED%8B%80%ED%90%81%EB%8B%B9-u4bgcmjx32xr/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%A6%AC%ED%8B%80%ED%90%81%EB%8B%B9%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%9A%A9%EC%9D%B8%EC%8B%9C%20%EA%B8%B0%ED%9D%A5%EA%B5%AC%20%ED%9D%A5%EB%8D%952%EB%A1%9C75%EB%B2%88%EA%B8%B8%2025-6',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '모래놀이와 워터룸을 결합한 프리미엄 실내 공간. 영유아 동반 예약형 놀이 후보로 둔다.',
    address: '경기도 용인시 기흥구 흥덕2로75번길 25-6',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-bundle-of-joy-gwangmyeong',
    name: 'Bundle of Joy 토들러카페 광명본점',
    region: 'gyeonggi-south',
    subRegion: '광명시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/bundle-of-joy-%ED%86%A0%EB%93%A4%EB%9F%AC%EC%B9%B4%ED%8E%98-10633776/',
    naverMapUrl: 'https://map.naver.com/p/search/Bundle%20of%20Joy%20%ED%86%A0%EB%93%A4%EB%9F%AC%EC%B9%B4%ED%8E%98%20%EA%B4%91%EB%AA%85%EB%B3%B8%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B4%91%EB%AA%85%EC%8B%9C%20%EC%98%A4%EB%A6%AC%EB%A1%9C%20970',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '40개월 미만 영유아 중심 토들러카페. 영아·토들러 특화 후보로 분리해 관리한다.',
    address: '경기도 광명시 오리로 970',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-funplry-uiwang',
    name: '펀플리 프라이빗 키즈&파티룸',
    region: 'gyeonggi-south',
    subRegion: '의왕시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%ED%8E%80%ED%94%8C%EB%A6%AC-%ED%82%A4%EC%A6%88-%ED%8C%8C%ED%8B%B0%EB%A3%B8-1719543/',
    naverMapUrl: 'https://map.naver.com/p/search/%ED%8E%80%ED%94%8C%EB%A6%AC%20%ED%94%84%EB%9D%BC%EC%9D%B4%EB%B9%97%20%ED%82%A4%EC%A6%88%26%ED%8C%8C%ED%8B%B0%EB%A3%B8%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%9D%98%EC%99%95%EC%8B%9C%20%EC%99%95%EC%86%8C%EB%82%98%EB%AC%B4%EA%B8%B8%2022-1',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '프라이빗 무인 키즈파티룸. 당근 업체 프로필과 비즈 소식에서 운영 신호가 반복 확인된다.',
    address: '경기도 의왕시 왕소나무길 22-1',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-byeolsup-kidsroom-gunpo',
    name: '별숲 키즈룸',
    region: 'gyeonggi-south',
    subRegion: '군포시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://www.daangn.com/kr/local-profile/%25EB%25B3%2584%25EC%2588%25B2-px9dcjycrpci/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%B3%84%EC%88%B2%20%ED%82%A4%EC%A6%88%EB%A3%B8%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B5%B0%ED%8F%AC%EC%8B%9C%20%EA%B8%88%EC%A0%95%EB%A1%9C%2047%20%EB%94%94%EC%8B%B8%EC%9D%B4%ED%8A%B8%201%EB%8F%99%204%EC%B8%B5%20401%ED%98%B8',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'semi_verified',
    description:
      '군포 금정동 프라이빗 무인 키즈카페. 네이버 예약과 시즌 공지 신호가 확인된다.',
    address: '경기도 군포시 금정로 47 디싸이트 1동 4층 401호',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ballbearpark-bucheon',
    name: '볼베어파크 부천점',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'http://www.ballbearpark.com/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%B3%BC%EB%B2%A0%EC%96%B4%ED%8C%8C%ED%81%AC%20%EB%B6%80%EC%B2%9C%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EB%B6%80%EC%B2%9C%EC%8B%9C%20%EC%9B%90%EB%AF%B8%EA%B5%AC%20%EC%A1%B0%EB%A7%88%EB%A3%A8%EB%A1%9C%202%20%EC%9B%85%EC%A7%84%ED%94%8C%EB%A0%88%EC%9D%B4%EB%8F%84%EC%8B%9C%202%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '스포츠존, 챌린저존, 디지털존, 영유아존을 갖춘 실내 스포츠 테마파크. 부천권 대형 키즈카페 후보로 우선순위가 높다.',
    address: '경기도 부천시 원미구 조마루로 2 웅진플레이도시 2층',
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-jumping-park-jeongja',
    name: '점핑파크 정자점',
    region: 'gyeonggi-south',
    subRegion: '수원시 장안구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=e087cbcb-0e8a-434c-b6c2-f005b5f012da',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%A0%90%ED%95%91%ED%8C%8C%ED%81%AC%20%EC%A0%95%EC%9E%90%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%88%98%EC%9B%90%EC%8B%9C%20%EC%9E%A5%EC%95%88%EA%B5%AC%20%EB%8C%80%ED%8F%89%EB%A1%9C%20128',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '600평 규모로 소개된 대형 트램폴린·스포츠형 키즈카페. 유치부와 초등·중등 공간이 분리된 활동형 공간이다.',
    address: '경기도 수원시 장안구 대평로 128',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
  },
  {
    id: 'gyeonggi-south-ground-planet-seoul-grand-park',
    name: '그라운드플래닛 서울대공원점',
    region: 'gyeonggi-south',
    subRegion: '과천시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.koreatriptips.com/tourist-attractions/2747760.html',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%B7%B8%EB%9D%BC%EC%9A%B4%EB%93%9C%ED%94%8C%EB%9E%98%EB%8B%9B%20%EC%84%9C%EC%9A%B8%EB%8C%80%EA%B3%B5%EC%9B%90%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EA%B3%BC%EC%B2%9C%EC%8B%9C%20%EB%8C%80%EA%B3%B5%EC%9B%90%EA%B4%91%EC%9E%A5%EB%A1%9C%2080',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '구 플레이월드로 알려진 서울대공원 인근 대형 실내 키즈 어드벤처. 어트랙션, 공연, 카페 동선을 함께 묶기 좋은 테마형 키즈카페다.',
    address: '경기도 과천시 대공원광장로 80',
    priceInfo: '유료 / 이용권·시즌별 변동',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
    editorNote:
      '상호 변경 이력이 있어 발행 전 현 상호, 운영시간, 예매 링크를 한 번 더 확인하는 편이 안전하다.',
  },
  {
    id: 'gyeonggi-south-dinosaur-world-siheung',
    name: '공룡월드 시흥점',
    region: 'gyeonggi-south',
    subRegion: '시흥시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.waug.com/ko/activities/145354',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%B3%B5%EB%A3%A1%EC%9B%94%EB%93%9C%20%EC%8B%9C%ED%9D%A5%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '공룡 전시, 공룡쇼, 마술쇼, 풍선쇼, 키즈카페형 놀이를 결합한 공룡 테마 실내 놀이공간. 공룡을 좋아하는 유아·초등 저학년에게 적합하다.',
    priceInfo: '유료 / 온라인 입장권 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'WAUG 판매 페이지로 운영 신호를 확인했다. 주소, 주차, 회차, 공연시간은 발행 전 공식 예약·전화로 재확인 필요.',
  },
  {
    id: 'gyeonggi-south-dinosaur-world-yongin',
    name: '공룡월드 용인점',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://travel.interpark.com/tna/products/b71f4baa-ced2-4dce-9cba-bba94c6aee69',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%B3%B5%EB%A3%A1%EC%9B%94%EB%93%9C%20%EC%9A%A9%EC%9D%B8%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '공룡 테마 전시와 공연, 키즈카페형 놀이를 함께 제공하는 실내 테마 키즈카페 후보. 비 오는 날 공룡 테마 나들이로 묶기 좋다.',
    priceInfo: '유료 / 온라인 입장권 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'NOL 인터파크 판매 페이지로 운영 신호를 확인했다. 상세 주소와 주차 지원은 발행 전 재확인 필요.',
  },
  {
    id: 'gyeonggi-south-dinosaur-world-dongtan',
    name: '공룡월드 동탄점',
    region: 'gyeonggi-south',
    subRegion: '화성시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.waug.com/ko/activities/150263',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%B3%B5%EB%A3%A1%EC%9B%94%EB%93%9C%20%EB%8F%99%ED%83%84%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '공룡 전시와 공연형 콘텐츠, 에어바운스·키즈카페 놀이를 결합한 동탄권 공룡 테마 실내 공간.',
    priceInfo: '유료 / 온라인 입장권 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'WAUG 판매 페이지로 운영 신호를 확인했다. 신규·이벤트성 운영 가능성이 있어 발행 전 최신 운영 공지를 확인해야 한다.',
  },
  {
    id: 'gyeonggi-south-zoolungzoolung-hanam',
    name: '주렁주렁 하남점',
    region: 'gyeonggi-south',
    subRegion: '하남시',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.zoolungzoolung.com/benefits_hanam',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%A3%BC%EB%A0%81%EC%A3%BC%EB%A0%81%20%ED%95%98%EB%82%A8%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%95%98%EB%82%A8%EC%8B%9C%20%EB%AF%B8%EC%82%AC%EB%8C%80%EB%A1%9C%20750%20%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%20%ED%95%98%EB%82%A8',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '실내에서 동물을 가까이 만나는 애니멀 테마파크. 키즈카페보다는 동물교감형 실내 체험시설에 가깝다.',
    address: '경기도 하남시 미사대로 750 스타필드 하남',
    priceInfo: '유료 / 하남점 공식 요금 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '동물교감형 테마 후보. 먹이주기, 체험 운영 여부와 요금은 하남점 공식 페이지 기준으로 확인한다.',
  },
  {
    id: 'gyeonggi-south-pororo-theme-park-dasan',
    name: '뽀로로테마파크 다산점',
    region: 'gyeonggi-south',
    subRegion: '남양주시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.pororopark.com/information/serviceHours.php',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%BD%80%EB%A1%9C%EB%A1%9C%ED%85%8C%EB%A7%88%ED%8C%8C%ED%81%AC%20%EB%8B%A4%EC%82%B0%EC%A0%90%20%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EB%82%A8%EC%96%91%EC%A3%BC%EC%8B%9C%20%EB%8B%A4%EC%82%B0%EC%A7%80%EA%B8%88%EB%A1%9C%20202',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '뽀로로 캐릭터를 기반으로 한 미취학 친화 실내 키즈 테마파크. 캐릭터형 키즈카페 seed로 묶기 좋다.',
    address: '경기도 남양주시 다산지금로 202',
    priceInfo: '유료 / 지점·시즌별 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '행정 구분상 남양주는 경기북부권으로도 볼 수 있으나, 기존 README 지역 구분의 남양주 예시와 충돌 가능성이 있어 후속 정리 필요.',
  },
  {
    id: 'gyeonggi-south-pororo-park-ansan',
    name: '뽀로로파크 안산점',
    region: 'gyeonggi-south',
    subRegion: '안산시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.pororopark.com/information/serviceHours.php',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%BD%80%EB%A1%9C%EB%A1%9C%ED%8C%8C%ED%81%AC%20%EC%95%88%EC%82%B0%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '뽀로로 캐릭터 테마의 실내 키즈파크. 영유아와 미취학 아동에게 익숙한 캐릭터형 실내 나들이 후보.',
    priceInfo: '유료 / 지점·시즌별 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 이용시간 페이지에서 지점 운영 여부를 확인했다. 주소, 주차, 요금은 발행 전 최신 예매 화면으로 재확인 필요.',
  },
  {
    id: 'ansan-astro-camp',
    name: '안산어린이천문대',
    region: 'gyeonggi-south',
    subRegion: '안산시',
    category: 'experience',
    ageBands: ['6-10y', 'all'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://cafe.naver.com/astroansan',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37458087',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '안산시에서 운영하는 공공 천문대. 낮 관람과 야간 별자리 관측 프로그램 운영.',
    address: '경기 안산시 상록구 반월로 399',
    operatingHours: '14:00-22:00 (월·화 휴관, 시즌별 변동)',
    priceInfo: '어린이 1,000원, 청소년 1,500원, 성인 2,000원',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '야간 관측 프로그램은 초등학생 이상 적합',
  },
  {
    id: 'everland',
    name: '에버랜드',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.everland.com/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11574457',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description: '국내 최대 테마파크. 어린이 전용 존과 동물원, 워터파크 포함.',
    address: '경기 용인시 처인구 포곡읍 에버랜드로 199',
    operatingHours: '10:00-21:00 (시즌별 변동)',
    priceInfo:
      '어린이 50,000원대, 성인 60,000원대 (자유이용권 기준, 변동 가능)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 480,
    operatorType: 'commercial',
    editorNote: '가격·운영시간은 시즌마다 바뀜. 공식 홈페이지 사전 확인 필수',
    thumbnailImage: '/images/places/everland.webp',
  },
  {
    id: 'gyeonggi-children-museum',
    name: '경기도어린이박물관',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://gcm.ggcf.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13172610',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '경기도가 운영하는 어린이 전용 체험 박물관. 영유아부터 초등학생까지 대상별 전시 공간.',
    address: '경기 용인시 기흥구 상갈로 6',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    priceInfo: '어린이·성인 모두 4,000원',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '사전 예약 필수. 주말 예약 빠르게 마감',
    thumbnailImage: '/images/places/gyeonggi-children-museum.webp',
  },
  {
    id: 'korea-folk-village',
    name: '한국민속촌',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'culture',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.koreanfolk.co.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620801',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '전통 한국 생활문화를 체험할 수 있는 야외 테마 공원. 계절별 전통 공연과 체험 운영.',
    address: '경기 용인시 기흥구 민속촌로 90',
    operatingHours: '09:30-18:00 (시즌별 변동)',
    priceInfo: '어린이 15,000원, 성인 25,000원 (변동 가능)',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote: '비포장 구간 있어 유모차 이동 어려움. 걷기 편한 신발 필수',
    thumbnailImage: '/images/places/korea-folk-village.webp',
  },
  {
    id: 'siheung-kids-cafe-sample',
    name: '시흥 키즈카페 (대형 복합형)',
    region: 'gyeonggi-south',
    subRegion: '시흥시',
    category: 'kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'discovery',
    sourceUrl: 'https://map.naver.com/',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%8B%9C%ED%9D%A5%20%ED%82%A4%EC%A6%88%EC%B9%B4%ED%8E%98%20(%EB%8C%80%ED%98%95%20%EB%B3%B5%ED%95%A9%ED%98%95)%20%EA%B2%BD%EA%B8%B0%20%EC%8B%9C%ED%9D%A5%EC%8B%9C%20%EC%9D%BC%EB%8C%80',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'needs_refresh',
    description:
      '시흥 소재 대형 키즈카페 대표 샘플. 실제 발행 전 공식 확인 필요.',
    address: '경기 시흥시 일대',
    priceInfo: '시간제 이용 (업체별 상이, 약 10,000~15,000원)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '이 항목은 discovery 상태로 공식 검증 전 발행 불가. 실제 운영 업체 직접 확인 필요',
  },
  {
    id: 'seongnam-isarang-playground-sunae',
    name: '수내 아이사랑놀이터',
    region: 'gyeonggi-south',
    subRegion: '성남시 분당구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.sneducare.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/35452365',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '분당 생활권에서 이용하기 좋은 공공 실내 놀이터. 부모와 영유아가 함께 머물며 짧게 놀기 좋은 동네 거점이다.',
    address: '경기도 성남시 분당구 황새울로240번길 10-5 3층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '네이버 지도와 리서치 문서 모두 수내 아이사랑놀이터 표기를 사용한다.',
  },
  {
    id: 'bucheon-ilovemom-cafe-bambak',
    name: '범박휴먼시아 아이러브맘카페',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.bucheoni.or.kr/ilove/branch_guide.asp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/35623918',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '부천 범박 생활권에서 이용하기 좋은 공공 아이러브맘카페. 영유아와 보호자가 함께 머물기 좋은 생활권 실내 공간이다.',
    address: '경기도 부천시 양지로 20 범박휴먼시아 1단지 관리동 2층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공식 사이트와 네이버 지도에서 범박휴먼시아 지점을 교차 확인했다.',
  },
  {
    id: 'bucheon-ilovemom-cafe-simgokbon',
    name: '심곡본동 아이러브맘카페',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.bucheoni.or.kr/center/branch_guide6.asp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1997092623',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '부천 원도심 생활권 부모와 영유아가 함께 이용하는 공공 아이러브맘카페. 가까운 실내 육아 보조 동선으로 쓰기 좋다.',
    address: '경기도 부천시 소사구 성주로249번길 19 행정복지센터 3층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '네이버 지도는 행정복지센터 3층 아이러브맘카페 표기를 사용한다.',
  },
  {
    id: 'bucheon-ilovemom-cafe-gogangbon',
    name: '고강본동 아이러브맘카페',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://www.bucheoni.or.kr/center/center_guide4_3.asp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/34026087',
    verifiedAt: '2026-04-14',
    lastObservedAt: '2026-04-14',
    verificationStatus: 'official_verified',
    description:
      '부천 서부 생활권에서 이용하기 좋은 공공 아이러브맘카페. 영유아와 보호자가 짧게 머물며 놀기 좋은 동네 공간이다.',
    address: '경기도 부천시 오정구 고리울로 79 신축건물 2층',
    priceInfo: '센터 문의 / 지점 운영 방식 확인',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '네이버 지도와 리서치 문서 모두 고강본동 지점 표기를 사용한다.',
  },
  {
    id: 'suwon-hwaseong-fortress',
    name: '수원화성',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'culture',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'outdoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.swcf.or.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13491459',
    verifiedAt: '2026-04-01',
    lastObservedAt: '2026-04-01',
    verificationStatus: 'official_verified',
    description:
      '유네스코 세계문화유산 수원화성. 성곽 둘레길과 행궁 관람, 전통 무예 공연 포함.',
    address: '경기 수원시 팔달구 행궁로 11',
    operatingHours: '09:00-18:00 (연중무휴, 시즌별 변동)',
    priceInfo: '어린이 700원, 성인 1,500원',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 150,
    operatorType: 'public',
    editorNote:
      '성곽 둘레길은 유모차 이동 어려움. 화성행궁 실내 관람 위주 권장',
    thumbnailImage: '/images/places/suwon-hwaseong-fortress.webp',
  },
  {
    id: 'gwangmyeong-cave',
    name: '광명동굴',
    region: 'gyeonggi-south',
    subRegion: '광명시',
    category: 'experience',
    ageBands: ['3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.gm.go.kr/cv/gc/CVGC_14000.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/21154281',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '동굴 산책과 미디어 공간을 함께 즐길 수 있는 광명 대표 실내외 나들이 명소. 더운 날이나 비 오는 날에도 동선을 짜기 좋다.',
    address: '경기도 광명시 가학로85번길 142',
    operatingHours: '09:00-18:00 (마지막 입장 17:00)',
    priceInfo: '36개월 미만 무료 / 황금패 달기 5,000원 별도',
    feedingRoom: true,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '수유실과 주차는 공식 안내에서 확인됐다. 동굴 구간 특성상 유모차 반입은 어렵다.',
    thumbnailImage: '/images/places/gwangmyeong-cave.webp',
  },
  {
    id: 'champion-black-belt-bucheon',
    name: '챔피언 더 블랙벨트 스타필드 시티 부천',
    region: 'gyeonggi-south',
    subRegion: '부천시',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/bucheon/entertainment/champion.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1021615583',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '스타필드 시티 부천 안에 있는 체험형 실내놀이터. 몸을 크게 쓰는 어드벤처 코스를 2시간 단위로 이용하기 좋다.',
    address: '경기도 부천시 옥길로 1',
    priceInfo: '23,000원 / 2시간',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '키 150cm 이하 어린이 기준. 쇼핑몰 내부 동선과 함께 묶어 방문하기 좋다.',
    thumbnailImage: '/images/places/champion-black-belt-bucheon.webp',
  },
  {
    id: 'champion-black-belt-suwon',
    name: '챔피언 더 블랙벨트 스타필드 수원',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/suwon/entertainment/champion.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1303740324',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '클라이밍과 네트 코스를 중심으로 구성된 대형 실내놀이터. 활동량이 많은 아이와 2시간 정도 머물기 좋은 공간.',
    address: '경기도 수원시 장안구 수성로 175',
    priceInfo: '평일 25,000원 / 주말 29,000원 / 2시간',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '키 150cm 이하 어린이 기준. 스타필드 수원 내부 시설이라 날씨 영향을 덜 받는다.',
    thumbnailImage: '/images/places/champion-black-belt-suwon.webp',
  },
  {
    id: 'byeolmadang-kids-suwon',
    name: '별마당 키즈 스타필드 수원',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/suwon/starfieldLibrary/kids.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1222095968',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '아이들이 머물며 책과 놀이를 함께 즐길 수 있게 만든 도서관형 실내 공간. 스타필드 수원 내부에서 가볍게 들르기 좋다.',
    address: '경기도 수원시 장안구 수성로 175',
    operatingHours: '10:00-22:00',
    priceInfo: '공식 페이지 별도 요금 표기 없음',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
    editorNote:
      '공식 소개 페이지에 아동 특화 도서관 설명이 있고 별도 이용요금 표기는 없다.',
    thumbnailImage: '/images/places/byeolmadang-kids-suwon.webp',
  },
  {
    id: 'byeolmadang-kids-anseong',
    name: '별마당 키즈 스타필드 안성',
    region: 'gyeonggi-south',
    subRegion: '안성시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.starfield.co.kr/anseong/entertainment/libraryKids.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1060401352',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '책 읽기와 가벼운 놀이를 함께 할 수 있는 아동 특화 도서관형 공간. 스타필드 안성 실내 동선 안에서 쉬어가기 좋다.',
    address: '경기 안성시 공도읍 서동대로 3930-39',
    operatingHours: '10:00-22:00',
    priceInfo: '공식 페이지 별도 요금 표기 없음',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
    editorNote:
      '공식 소개 페이지에 아동 특화 도서관 설명이 있고 별도 이용요금 표기는 없다.',
    thumbnailImage: '/images/places/byeolmadang-kids-anseong.webp',
  },
  {
    id: 'toy-kingdom-suwon',
    name: '토이킹덤 스타필드 수원',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/suwon/anchorTenant/toyKingdom.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1511045789',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '장난감 체험과 시연 동선이 함께 있는 어린이 체험형 장난감 공간. 스타필드 수원에서 쇼핑과 함께 들르기 좋다.',
    address: '경기도 수원시 장안구 수성로 175',
    operatingHours: '10:00-22:00',
    priceInfo: '공식 페이지 별도 요금 표기 없음',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
    editorNote:
      '공식 페이지에 어린이 체험 시설 설명이 있으며 별도 이용요금 표기는 없다.',
    thumbnailImage: '/images/places/toy-kingdom-suwon.webp',
  },
  {
    id: 'toy-kingdom-anseong',
    name: '토이킹덤 스타필드 안성',
    region: 'gyeonggi-south',
    subRegion: '안성시',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.starfield.co.kr/anseong/anchorTenant/toyKingdom.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1062375436',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '장난감 시연과 체험 구성이 함께 있는 어린이 체험형 장난감 공간. 스타필드 안성 내부에서 짧게 들르기 좋다.',
    address: '경기 안성시 공도읍 서동대로 3930-39',
    operatingHours: '10:00-22:00',
    priceInfo: '공식 페이지 별도 요금 표기 없음',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'commercial',
    editorNote:
      '공식 페이지에 체험 시설 설명은 있으나 별도 이용요금 표기는 없다.',
    thumbnailImage: '/images/places/toy-kingdom-anseong.webp',
  },
  {
    id: 'yongin-children-imagination-forest',
    name: '용인어린이상상의숲',
    region: 'gyeonggi-south',
    subRegion: '용인시',
    category: 'culture',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.yicf.or.kr/lib/mainPage.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1865643212',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '공연, 미술, 감각 놀이를 함께 묶은 어린이 문화예술 복합공간. 실내 전시와 야외 광장을 한 번에 둘러보기 좋다.',
    address: '경기도 용인시 처인구 동백죽전대로 61',
    operatingHours: '화-일 운영 (프로그램별 상이)',
    priceInfo: '무료 공간과 유료 체험 프로그램이 함께 운영됨',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      'VIP A 주차장과 지하 주차장을 이용할 수 있다. 프로그램별 예약 여부와 이용료는 방문 전 다시 확인하는 편이 안전하다.',
  },
  {
    id: 'korea-job-world-children-experience-center',
    name: '한국잡월드 어린이체험관',
    region: 'gyeonggi-south',
    subRegion: '성남시',
    category: 'experience',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.koreajobworld.or.kr/main.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13463552',
    verifiedAt: '2026-04-06',
    lastObservedAt: '2026-04-06',
    verificationStatus: 'official_verified',
    description:
      '아이 눈높이에서 직업 체험을 구성한 대형 실내 체험관. 하루 일정으로 길게 머물며 체험하기 좋다.',
    address: '경기도 성남시 분당구 분당수서로 501',
    priceInfo: '어린이체험관 일반권·단체권 운영',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'public',
    editorNote:
      '만 4세 이상 중심 시설이다. 공식 예약 시스템과 주차 안내를 함께 확인하고 움직이는 편이 좋다.',
  },
  {
    id: 'aquaplanet-gwanggyo',
    name: '아쿠아플라넷 광교',
    region: 'gyeonggi-south',
    subRegion: '수원시',
    category: 'experience',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.aquaplanet.co.kr/gwanggyo/information/use_price.do',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1375547224',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '광교호수공원 실내 동선 안에서 해양 생물을 가까이 볼 수 있는 아쿠아리움. 비 오는 날 대체 코스로 쓰기 좋다.',
    address: '경기도 수원시 영통구 광교호수공원로 300',
    priceInfo: '36개월 미만 무료',
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 안내에 유모차·휠체어 대여와 주차 인증 기준이 함께 노출된다. 36개월 미만 무료는 직계가족 동반과 증빙 기준을 다시 확인해야 한다.',
  },
  {
    id: 'railroad-museum',
    name: '철도박물관',
    region: 'gyeonggi-south',
    subRegion: '의왕시',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.railroadmuseum.co.kr/page/information',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620699',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '철도 차량과 실내 전시를 함께 볼 수 있는 철도 테마 박물관. 기차를 좋아하는 아이와 하루 코스를 짜기 좋다.',
    address: '경기도 의왕시 철도박물관로 142',
    operatingHours: '09:30-17:00 (동절기 기준)',
    priceInfo: '일반 4,000원 / 어린이·청소년 2,000원 / 48개월 미만 무료',
    feedingRoom: true,
    strollerFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '공식 관람안내와 오시는 길에서 무료 주차를 확인했다. 야외 차량 전시는 날씨 영향을 받는다.',
  },
] satisfies PlaceSource[];
