import type { PlaceSource } from '../../../types/place-source.ts';

const INCHEON_DREAM_CENTER_SOURCE_URL =
  'https://www.incheon.go.kr/icbenefit/ICB020201/?curPage=5&srchField=%EB%B3%B4%EC%9C%A1%EA%B5%90%EC%9C%A1&srchSupport=&srchUserType=&srchWord=';

export const INCHEON_PLACES = [
  {
    id: 'incheon-aisarang-dream-center-jung-gu-1',
    name: '아이사랑꿈터 중구 1호점',
    region: 'incheon',
    subRegion: '중구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1407229169',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자와 영유아가 함께 머무는 공공 실내 놀이공간. 영종 생활권에서 짧게 들르기 좋은 영아 친화 거점이다.',
    address: '인천 중구 신도시남로 15 103동 104호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공식 포털에 운서동 지점명과 전화가 노출된다. 회차와 프로그램 대상은 방문 전 다시 확인하는 편이 안전하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-dong-gu-1',
    name: '아이사랑꿈터 동구 1호점',
    region: 'incheon',
    subRegion: '동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1877329928',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자 동반 영유아를 위한 공공 놀이공간. 주민행복센터 안에 있어 동네 육아 동선에 넣기 쉽다.',
    address: '인천 동구 염전로40번길 70 주민행복센터 2층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '주민행복센터 연계형 지점이다. 세부 운영 시간보다는 프로그램 공지 중심으로 확인하는 편이 좋다.',
  },
  {
    id: 'incheon-aisarang-dream-center-michuhol-gu-1',
    name: '아이사랑꿈터 미추홀구 1호점',
    region: 'incheon',
    subRegion: '미추홀구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1057272282',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '공동주택 생활권 안에서 이용할 수 있는 공공 영유아 놀이공간. 짧은 체류 위주의 실내 육아 쉼터로 쓰기 좋다.',
    address: '인천 미추홀구 숙골로112번길 12 도화서희스타힐스 크루즈시티 B103-2호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '도화권 공동주택 상가형 지점이다. 외부 방문자 주차 여부는 이번 차수에서 확인하지 못했다.',
  },
  {
    id: 'incheon-aisarang-dream-center-yeonsu-gu-2',
    name: '아이사랑꿈터 연수구 2호점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1810350999',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '송도 공동주택 생활권에서 이용하기 좋은 공공 영유아 놀이공간. 날씨에 덜 영향을 받는 실내 육아 동선 후보다.',
    address: '인천 연수구 송도문화로28번길 81 송도 더샾그린스퀘어 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '송도 공동주택형 지점이다. 프로그램별 연령 기준이 달라 신청 전 대상 확인이 필요하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-namdong-gu-4',
    name: '아이사랑꿈터 남동구 4호점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1276800679',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '남동구 에코메트로 생활권에서 접근하기 쉬운 공공 놀이공간. 영유아와 보호자가 함께 머물기 좋은 소규모 실내 공간이다.',
    address: '인천 남동구 논현로 106 에코메트로한화꿈에그린 608동 B1 관리사무소 옆',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '공동주택 단지형 지점이라 외부 주차 가능 여부보다 프로그램 접근성을 우선 확인하는 편이 좋다.',
  },
  {
    id: 'incheon-aisarang-dream-center-gyeyang-gu-4',
    name: '아이사랑꿈터 계양구 4호점',
    region: 'incheon',
    subRegion: '계양구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1646319802',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '생활문화센터 안에 들어선 공공 영유아 놀이공간. 짧은 놀이와 부모 휴식 동선을 함께 잡기 쉽다.',
    address: '인천 계양구 장제로 853 계양2동 생활문화센터 4층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '생활문화센터형 지점이다. 층수 이동이 있어 유모차 동선은 현장 여건을 다시 보는 편이 안전하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-1',
    name: '아이사랑꿈터 서구 1호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1093768329',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '루원시티권에서 이용하기 좋은 공공 영유아 놀이공간. 생활권 안에서 비 오는 날 대안 동선으로 활용하기 좋다.',
    address: '인천 서구 봉오재1로 36 루원센트럴타운 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '루원시티 공동주택형 지점이다. 공식 포털에는 신현동 표기가 함께 노출된다.',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-4',
    name: '아이사랑꿈터 서구 4호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/572996995',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '청라 생활권 보호자와 영유아를 위한 공공 놀이공간. 주민공동시설 기반이라 가까운 실내 육아 거점으로 쓰기 좋다.',
    address: '인천 서구 청라한내로 40 청라호수공원한신더휴 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote: '청라 공동주택형 지점이다. 프로그램 운영일과 신청 방식은 공식 공지를 다시 확인해야 한다.',
  },
  {
    id: 'incheon-children-science-museum',
    name: '인천어린이과학관',
    region: 'incheon',
    subRegion: '계양구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.insiseol.or.kr/culture/icsmuseum/introduction/preview.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19545719',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '영유아 전용 무지개마을 구역이 함께 있는 어린이 과학관. 회차별 예약제로 어린 아이와도 비교적 안정적으로 움직이기 좋다.',
    address: '인천광역시 계양구 방축로21',
    operatingHours: '09:00-18:00 (회차별 사전 온라인 예약제)',
    priceInfo: '어린이·청소년 2,000원 / 성인 4,000원 / 보호자 동반 만 6세 이하 무료',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '공식 사이트에 예약, 편의시설, 주차장안내 메뉴가 함께 노출된다. 상설전시관은 회차별 사전예약제로 운영된다.',
  },
  {
    id: 'incheon-student-science-museum',
    name: '인천학생과학관',
    region: 'incheon',
    subRegion: '중구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://science.ice.go.kr/msi/cntntsService.do?menuId=MNU_0000000000000082',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19801527',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '무료로 가볍게 들르기 좋은 과학 체험 공간. 개별 관람은 현장 접수라 영종권 실내 나들이 후보로 묶기 쉽다.',
    address: '인천광역시 중구 영종대로 277번길 74-10',
    operatingHours: '화~일 운영 / 개별 관람 현장 접수',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '개별 관람은 현장 접수, 단체 관람은 사전 예약 승인 후 이용한다. 천체투영실은 6세 이상 중심이다.',
  },
  {
    id: 'oktokki-space-center',
    name: '옥토끼우주센터',
    region: 'incheon',
    subRegion: '강화군',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.oktokki.com/about/fees',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12090933',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '우주과학 테마 전시와 야외 체험 동선을 함께 묶은 강화 대표 가족형 시설. 하루 일정으로 넉넉하게 잡는 편이 잘 맞는다.',
    address: '인천광역시 강화군 불은면 강화동로 403',
    operatingHours: '평일 10:00-17:30 / 주말·공휴일 09:30-19:00',
    priceInfo: '24~36개월 미만 13,000원 / 36개월~12세 18,800원 / 13세 이상 19,800원 / 24개월 미만 무료',
    rainFriendly: false,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote: '24개월 미만은 무료지만 일부 시설 이용 제한이 있을 수 있다. 야외 체험 비중이 있어 날씨 영향을 고려하는 편이 좋다.',
  },
] satisfies PlaceSource[];
