import type { PlaceSource } from '../../../types/place-source.ts';

const INCHEON_DREAM_CENTER_SOURCE_URL =
  'https://www.incheon.go.kr/icbenefit/ICB020201/?curPage=5&srchField=%EB%B3%B4%EC%9C%A1%EA%B5%90%EC%9C%A1&srchSupport=&srchUserType=&srchWord=';

export const INCHEON_PLACES = [
  {
    id: 'incheon-oktokki-space-center',
    name: '옥토끼우주센터',
    region: 'incheon',
    subRegion: '강화군',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    seasons: ['all-season', 'spring', 'fall'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.oktokki.com/about/fees',
    naverMapUrl:
      'https://map.naver.com/p/search/%EC%98%A5%ED%86%A0%EB%81%BC%EC%9A%B0%EC%A3%BC%EC%84%BC%ED%84%B0%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EA%B0%95%ED%99%94%EA%B5%B0%20%EB%B6%88%EC%9D%80%EB%A9%B4%20%EA%B0%95%ED%99%94%EB%8F%99%EB%A1%9C%20403',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '우주과학 전시와 체험, 야외 놀이시설을 함께 이용하는 강화군 민간 우주과학 테마파크.',
    address: '인천광역시 강화군 불은면 강화동로 403',
    operatingHours: '평일 10:00-17:30 / 주말·공휴일 09:30-19:00',
    priceInfo:
      '24~36개월 미만 13,000원 / 36개월~12세 18,800원 / 13세 이상 19,800원 / 24개월 미만 무료',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
    thumbnailImage: '/images/places/incheon-oktokki-space-center.webp',
  },
  {
    id: 'incheon-naughty-child-cheongna',
    name: '너티차일드 청라점',
    region: 'incheon',
    subRegion: '서구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.naughtychild.co.kr/cheongna',
    naverMapUrl:
      'https://map.naver.com/p/search/%EB%84%88%ED%8B%B0%EC%B0%A8%EC%9D%BC%EB%93%9C%20%EC%B2%AD%EB%9D%BC%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EC%84%9C%EA%B5%AC%20%EC%B2%AD%EB%9D%BC%EC%97%90%EB%A9%94%EB%9E%84%EB%93%9C%EB%A1%9C%2079%20%EC%BB%A4%EB%82%BC%EC%97%90%EB%B9%84%EB%89%B4%20%EC%A7%80%ED%95%981%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '청라 커낼에비뉴 지하에 있는 프리미엄 키즈 테마파크. 카트, 볼풀, 낚시놀이 등 대형 키즈카페 성격이 강하다.',
    address: '인천광역시 서구 청라에메랄드로 79 커낼에비뉴 지하1층',
    operatingHours: '10:30-20:30',
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'commercial',
    thumbnailImage: '/images/places/incheon-naughty-child-cheongna.webp',
  },
  {
    id: 'incheon-champion-black-belt-homeplus-songdo',
    name: '챔피언더블랙벨트 홈플러스 인천송도점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://my.homeplus.co.kr/store/store_detail?storId=1196',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent('챔피언더블랙벨트 홈플러스 인천송도점 인천광역시 연수구 송도국제대로 165 홈플러스 인천송도점 1층')}`,
    verifiedAt: '2026-05-06',
    lastObservedAt: '2026-05-06',
    verificationStatus: 'semi_verified',
    description:
      '홈플러스 인천송도점 1층에 입점한 플레이타임 계열 스포츠형 키즈카페. 송도권 마트 연계 실내 놀이 후보로 적합하다.',
    address: '인천광역시 연수구 송도국제대로 165 홈플러스 인천송도점 1층',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '유료 / 지점 안내 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '홈플러스 공식 점포 페이지와 전국 플레이타임 직영점 매장 위치 안내 PDF에서 지점 신호를 확인했다.',
    thumbnailImage:
      '/images/places/incheon-champion-black-belt-homeplus-songdo.webp',
  },
  {
    id: 'incheon-baby-angels-homeplus-songdo',
    name: '베이비엔젤스 홈플러스 인천송도점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'baby-kids-cafe',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season', 'summer'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://my.homeplus.co.kr/store/store_detail?storId=1196',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent('베이비엔젤스 홈플러스 인천송도점 인천광역시 연수구 송도국제대로 165 홈플러스 인천송도점 1층')}`,
    verifiedAt: '2026-05-06',
    lastObservedAt: '2026-05-06',
    verificationStatus: 'semi_verified',
    description:
      '홈플러스 인천송도점 임대매장으로 확인되는 영유아 친화 실내 놀이·물놀이형 공간. 송도권 영아 동반 후보로 별도 관리한다.',
    address: '인천광역시 연수구 송도국제대로 165 홈플러스 인천송도점 1층',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '요금 확인 필요',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
    editorNote:
      '홈플러스 공식 점포 페이지에서 임대매장명을 확인했다. 수영·놀이 세부 운영 방식은 방문 전 재확인 필요.',
    thumbnailImage: '/images/places/incheon-baby-angels-homeplus-songdo.webp',
  },
  {
    id: 'incheon-champion-1250-guwol-traders',
    name: '챔피언1250 트레이더스 구월점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://westart.or.kr/wp-content/uploads/2026/04/%EC%A0%84%EA%B5%AD%ED%94%8C%EB%A0%88%EC%9D%B4%ED%83%80%EC%9E%84%EC%A7%81%EC%98%81%EC%A0%90%EB%A7%A4%EC%9E%A5%EC%9C%84%EC%B9%98%EC%95%88%EB%82%B4.pdf',
    naverMapUrl:
      'https://map.naver.com/p/search/%EC%B1%94%ED%94%BC%EC%96%B81250%20%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EC%8A%A4%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EB%82%A8%EB%8F%99%EA%B5%AC%20%EB%A7%A4%EC%86%8C%ED%99%80%EB%A1%9C%20759%20%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EC%8A%A4%20%ED%99%80%EC%84%B8%EC%9D%BC%ED%81%B4%EB%9F%BD%20%EA%B5%AC%EC%9B%94%EC%A0%90%201%EC%B8%B5',
    verifiedAt: '2026-05-06',
    lastObservedAt: '2026-05-06',
    verificationStatus: 'semi_verified',
    description:
      '트레이더스 구월점 1층 입점 신호가 있는 키즈 테마파크 후보. 스카이라인과 대형 어트랙션 중심으로 소개됐다.',
    address: '인천광역시 남동구 매소홀로 759 트레이더스 홀세일클럽 구월점 1층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '전국 플레이타임 직영점 매장 위치 안내 PDF와 오픈 보도자료를 함께 확인했다. 세부 요금과 휴무는 방문 전 재확인 필요.',
    thumbnailImage: '/images/places/incheon-champion-1250-guwol-traders.webp',
  },
  {
    id: 'incheon-monster-park-guwol',
    name: '몬스터파크 구월점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://my.homeplus.co.kr/store/store_detail?storId=1119',
    naverMapUrl:
      'https://map.naver.com/p/search/%EB%AA%AC%EC%8A%A4%ED%84%B0%ED%8C%8C%ED%81%AC%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EB%82%A8%EB%8F%99%EA%B5%AC%20%EC%98%88%EC%88%A0%EB%A1%9C%20198%20%ED%99%88%ED%94%8C%EB%9F%AC%EC%8A%A4%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%A7%80%ED%95%983%EC%B8%B5',
    verifiedAt: '2026-05-06',
    lastObservedAt: '2026-05-06',
    verificationStatus: 'semi_verified',
    description:
      '시간 무제한형 실내 테마파크 콘셉트의 구월동 대형 키즈카페 후보. 브랜드 공식 페이지와 구월점 운영 신호를 함께 확인했다.',
    address: '인천광역시 남동구 예술로 198 홈플러스 구월점 지하3층',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
    editorNote:
      '홈플러스 공식 점포 페이지에서 임대매장명을 확인했다. 세부 요금과 휴무는 방문 전 재확인 필요.',
    thumbnailImage: '/images/places/incheon-monster-park-guwol.webp',
  },
  {
    id: 'incheon-dinosaur-world',
    name: '공룡월드 인천점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'kids-cafe',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://travel.interpark.com/tna/products/b075a045-0eba-47a0-82db-01000367d6ae',
    naverMapUrl:
      'https://map.naver.com/p/search/%EA%B3%B5%EB%A3%A1%EC%9B%94%EB%93%9C%20%EC%9D%B8%EC%B2%9C%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '공룡 전시와 공연, 키즈카페형 놀이를 함께 묶은 인천권 공룡 테마 실내 공간. 공룡을 좋아하는 유아·초등 저학년 나들이 후보로 적합하다.',
    priceInfo: '유료 / 온라인 입장권 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'NOL 인터파크 판매 페이지로 운영 신호를 확인했다. 상세 주소, 주차, 공연 회차는 발행 전 재확인 필요.',
    thumbnailImage: '/images/places/incheon-dinosaur-world.webp',
  },
  {
    id: 'incheon-zoorarium-cheongna',
    name: '쥬라리움 청라점',
    region: 'incheon',
    subRegion: '서구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://zoorarium.com/cheongna',
    naverMapUrl:
      'https://map.naver.com/p/search/%EC%A5%AC%EB%9D%BC%EB%A6%AC%EC%9B%80%20%EC%B2%AD%EB%9D%BC%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '실내 동물원과 키즈카페 성격을 함께 가진 동물교감형 테마 공간. 날씨 영향을 덜 받고 동물 먹이주기·관찰 동선을 구성하기 좋다.',
    priceInfo: '유료 / 지점 공식 안내 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 청라점 페이지를 기준으로 넣었다. 동물 체험 운영, 요금, 휴무는 방문 전 공식 안내를 재확인해야 한다.',
    thumbnailImage: '/images/places/incheon-zoorarium-cheongna.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-jung-gu-1',
    name: '아이사랑꿈터 중구 1호점',
    region: 'incheon',
    subRegion: '중구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1407229169',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자와 영유아가 함께 머무는 공공 실내 놀이공간. 영종 생활권에서 짧게 들르기 좋은 영아 친화 거점이다.',
    address: '인천 중구 신도시남로 15 103동 104호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공식 포털에 운서동 지점명과 전화가 노출된다. 회차와 프로그램 대상은 방문 전 다시 확인하는 편이 안전하다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-jung-gu-1.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-dong-gu-1',
    name: '아이사랑꿈터 동구 1호점',
    region: 'incheon',
    subRegion: '동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1877329928',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자 동반 영유아를 위한 공공 놀이공간. 주민행복센터 안에 있어 동네 육아 동선에 넣기 쉽다.',
    address: '인천 동구 염전로40번길 70 주민행복센터 2층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '주민행복센터 연계형 지점이다. 세부 운영 시간보다는 프로그램 공지 중심으로 확인하는 편이 좋다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-dong-gu-1.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-michuhol-gu-1',
    name: '아이사랑꿈터 미추홀구 1호점',
    region: 'incheon',
    subRegion: '미추홀구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1057272282',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '공동주택 생활권 안에서 이용할 수 있는 공공 영유아 놀이공간. 짧은 체류 위주의 실내 육아 쉼터로 쓰기 좋다.',
    address:
      '인천 미추홀구 숙골로112번길 12 도화서희스타힐스 크루즈시티 B103-2호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '도화권 공동주택 상가형 지점이다. 외부 방문자 주차 여부는 이번 차수에서 확인하지 못했다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-michuhol-gu-1.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-yeonsu-gu-2',
    name: '아이사랑꿈터 연수구 2호점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1810350999',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '송도 공동주택 생활권에서 이용하기 좋은 공공 영유아 놀이공간. 날씨에 덜 영향을 받는 실내 육아 동선 후보다.',
    address: '인천 연수구 송도문화로28번길 81 송도 더샾그린스퀘어 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '송도 공동주택형 지점이다. 프로그램별 연령 기준이 달라 신청 전 대상 확인이 필요하다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-yeonsu-gu-2.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-namdong-gu-4',
    name: '아이사랑꿈터 남동구 4호점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1276800679',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '남동구 에코메트로 생활권에서 접근하기 쉬운 공공 놀이공간. 영유아와 보호자가 함께 머물기 좋은 소규모 실내 공간이다.',
    address:
      '인천 남동구 논현로 106 에코메트로한화꿈에그린 608동 B1 관리사무소 옆',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공동주택 단지형 지점이라 외부 주차 가능 여부보다 프로그램 접근성을 우선 확인하는 편이 좋다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-namdong-gu-4.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-gyeyang-gu-4',
    name: '아이사랑꿈터 계양구 4호점',
    region: 'incheon',
    subRegion: '계양구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1646319802',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '생활문화센터 안에 들어선 공공 영유아 놀이공간. 짧은 놀이와 부모 휴식 동선을 함께 잡기 쉽다.',
    address: '인천 계양구 장제로 853 계양2동 생활문화센터 4층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '생활문화센터형 지점이다. 층수 이동이 있어 유모차 동선은 현장 여건을 다시 보는 편이 안전하다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-gyeyang-gu-4.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-1',
    name: '아이사랑꿈터 서구 1호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1093768329',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '루원시티권에서 이용하기 좋은 공공 영유아 놀이공간. 생활권 안에서 비 오는 날 대안 동선으로 활용하기 좋다.',
    address: '인천 서구 봉오재1로 36 루원센트럴타운 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '루원시티 공동주택형 지점이다. 공식 포털에는 신현동 표기가 함께 노출된다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-seo-gu-1.webp',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-4',
    name: '아이사랑꿈터 서구 4호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/572996995',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '청라 생활권 보호자와 영유아를 위한 공공 놀이공간. 주민공동시설 기반이라 가까운 실내 육아 거점으로 쓰기 좋다.',
    address: '인천 서구 청라한내로 40 청라호수공원한신더휴 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '청라 공동주택형 지점이다. 프로그램 운영일과 신청 방식은 공식 공지를 다시 확인해야 한다.',
    thumbnailImage:
      '/images/places/incheon-aisarang-dream-center-seo-gu-4.webp',
  },
  {
    id: 'incheon-children-science-museum',
    name: '인천어린이과학관',
    linkedPostSlugs: ['incheon-children-science-museum-parking'],
    region: 'incheon',
    subRegion: '계양구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'partial-free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.insiseol.or.kr/culture/icsmuseum/introduction/preview.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19545719',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '영유아 전용 무지개마을 구역이 함께 있는 어린이 과학관. 회차별 예약제로 어린 아이와도 비교적 안정적으로 움직이기 좋다.',
    address: '인천광역시 계양구 방축로21',
    operatingHours: '09:00-18:00 (회차별 사전 온라인 예약제)',
    priceInfo:
      '어린이·청소년 2,000원 / 성인 4,000원 / 보호자 동반 만 6세 이하 무료',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '공식 사이트에 예약, 편의시설, 주차장안내 메뉴가 함께 노출된다. 상설전시관은 회차별 사전예약제로 운영된다.',
    thumbnailImage: '/images/places/incheon-children-science-museum.webp',
  },
  {
    id: 'incheon-student-science-museum',
    name: '인천학생과학관',
    linkedPostSlugs: ['incheon-student-science-museum-parking'],
    region: 'incheon',
    subRegion: '중구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://science.ice.go.kr/msi/cntntsService.do?menuId=MNU_0000000000000082',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19801527',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '무료로 가볍게 들르기 좋은 과학 체험 공간. 개별 관람은 현장 접수라 영종권 실내 나들이 후보로 묶기 쉽다.',
    address: '인천광역시 중구 영종대로 277번길 74-10',
    operatingHours: '화~일 운영 / 개별 관람 현장 접수',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '개별 관람은 현장 접수, 단체 관람은 사전 예약 승인 후 이용한다. 천체투영실은 6세 이상 중심이다.',
    thumbnailImage: '/images/places/incheon-student-science-museum.webp',
  },
  {
    id: 'oktokki-space-center',
    name: '옥토끼우주센터',
    region: 'incheon',
    subRegion: '강화군',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    seasons: ['all-season', 'spring', 'fall'],
    priceType: 'partial-free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.oktokki.com/about/fees',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12090933',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'needs_refresh',
    description:
      '우주과학 테마 전시와 야외 체험 동선을 함께 묶은 강화 대표 가족형 시설. 하루 일정으로 넉넉하게 잡는 편이 잘 맞는다.',
    address: '인천광역시 강화군 불은면 강화동로 403',
    operatingHours: '평일 10:00-17:30 / 주말·공휴일 09:30-19:00',
    priceInfo:
      '24~36개월 미만 13,000원 / 36개월~12세 18,800원 / 13세 이상 19,800원 / 24개월 미만 무료',
    rainFriendly: false,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote:
      '24개월 미만은 무료지만 일부 시설 이용 제한이 있을 수 있다. 야외 체험 비중이 있어 날씨 영향을 고려하는 편이 좋다. 기존 incheon-oktokki-space-center와 동일 장소라 중복 발행 방지를 위해 재검수 대상으로 둔다.',
  },
  {
    id: 'ganghwa-history-museum',
    name: '강화역사박물관',
    linkedPostSlugs: ['ganghwa-history-museum-parking'],
    region: 'incheon',
    subRegion: '강화군',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ganghwa.go.kr/open_content/museum_history/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12442027',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '강화도 선사부터 근현대까지 지역 역사를 한 번에 훑기 좋은 공공 박물관. 근처 자연사박물관과 함께 묶기 좋다.',
    address: '인천광역시 강화군 하점면 강화대로 994-19',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '강화권 공공 박물관 동선으로 자연사박물관과 함께 묶기 좋다.',
    thumbnailImage: '/images/places/ganghwa-history-museum.webp',
  },
  {
    id: 'ganghwa-natural-history-museum',
    name: '강화자연사박물관',
    linkedPostSlugs: ['ganghwa-natural-history-museum-parking'],
    region: 'incheon',
    subRegion: '강화군',
    category: 'museum',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ganghwa.go.kr/open_content/museum_natural/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37027622',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '공룡과 화석, 자연 생태 전시를 중심으로 아이들이 흥미를 느끼기 쉬운 강화권 자연사 박물관.',
    address: '인천광역시 강화군 하점면 강화대로 994-33',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '역사박물관과 가까워 강화권 실내 코스로 연계하기 쉽다.',
    thumbnailImage: '/images/places/ganghwa-natural-history-museum.webp',
  },
  {
    id: 'gyeyang-fortress-museum',
    name: '계양산성박물관',
    linkedPostSlugs: ['gyeyang-fortress-museum-parking'],
    region: 'incheon',
    subRegion: '계양구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://museum.gyeyang.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1464948902',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '산성 유적과 지역 역사를 어린이 눈높이 전시로 풀어낸 산성 전문 박물관. 계양산 나들이와 연결하기 좋다.',
    address: '인천광역시 계양구 계양산로 101',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 75,
    operatorType: 'public',
    editorNote:
      '전시 관람 뒤 계양산성 주변 산책 코스와 함께 묶는 동선이 자연스럽다.',
    thumbnailImage: '/images/places/gyeyang-fortress-museum.webp',
  },
  {
    id: 'national-institute-of-biological-resources',
    name: '국립생물자원관',
    linkedPostSlugs: ['national-institute-of-biological-resources-parking'],
    region: 'incheon',
    subRegion: '서구',
    category: 'museum',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.nibr.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12338771',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '생물 표본과 생태 전시를 중심으로 자연 관찰 흥미를 키우기 좋은 국립 기관 전시관.',
    address: '인천광역시 서구 환경로 42 국립생물자원관',
    operatingHours: '09:30-17:30 (월요일 휴관)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '전시 규모가 커서 초등 저학년까지 폭넓게 묶기 좋다.',
    thumbnailImage:
      '/images/places/national-institute-of-biological-resources.webp',
  },
  {
    id: 'incheon-safety-experience-center',
    name: '인천국민안전체험관',
    region: 'incheon',
    subRegion: '서구',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/119safe/index',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1649366728',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '재난과 생활안전 주제를 실습형으로 체험하는 대형 안전 체험관. 비 오는 날 실내 교육형 나들이로 잘 맞는다.',
    address: '인천광역시 서구 봉오재1로 120',
    operatingHours: '09:00-18:00 (월요일 휴관, 사전예약제)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '예약제 운영이라 회차를 먼저 잡고 움직이는 편이 안전하다.',
    thumbnailImage: '/images/places/incheon-safety-experience-center.webp',
  },
  {
    id: 'national-museum-of-world-writing',
    name: '국립세계문자박물관',
    linkedPostSlugs: ['national-museum-of-world-writing-parking'],
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.mow.or.kr/kor/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37162865',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '문자와 기록 문화를 시각적으로 풀어낸 국립 박물관. 송도 실내 문화 동선으로 묶기 좋다.',
    address: '인천광역시 연수구 센트럴로 217 국립세계문자박물관',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 전시 중심으로 가볍게 보기 좋고, 송도권 다른 실내 시설과 연계하기 쉽다.',
    thumbnailImage: '/images/places/national-museum-of-world-writing.webp',
  },
  {
    id: 'incheon-metropolitan-city-museum',
    name: '인천광역시립박물관',
    linkedPostSlugs: ['incheon-metropolitan-city-museum-parking'],
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/index',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620569',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '인천 지역사 전체를 폭넓게 다루는 대표 공공 박물관. 송도권 역사·전시 코스로 기본축이 되는 시설이다.',
    address: '인천광역시 연수구 청량로160번길 26 인천시립박물관',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '연수구 문화벨트 박물관 동선의 중심으로 묶기 좋다.',
    thumbnailImage: '/images/places/incheon-metropolitan-city-museum.webp',
  },
  {
    id: 'incheon-urban-history-museum',
    name: '인천도시역사관',
    linkedPostSlugs: ['incheon-urban-history-museum-parking'],
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/MU050101',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13294480',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '인천 도시 형성과 생활 변화를 중심으로 구성한 역사 전시관. 어린이 특별전이 함께 열리는 편이라 가족 관람에 무난하다.',
    address: '인천광역시 연수구 인천타워대로 238',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 75,
    operatorType: 'public',
    editorNote:
      '송도권 실내 문화시설을 묶는 코스에서 박물관 입문용으로 쓰기 좋다.',
    thumbnailImage: '/images/places/incheon-urban-history-museum.webp',
  },
  {
    id: 'national-incheon-marine-museum',
    name: '국립인천해양박물관',
    linkedPostSlugs: ['national-incheon-marine-museum-parking'],
    region: 'incheon',
    subRegion: '중구',
    category: 'museum',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://inmm.or.kr/page/ko/selectPage.do?menuSeq=3350&pageSeq=3716',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1648472832',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '해양사와 항만 문화를 현대적으로 풀어낸 국립 박물관. 월미권 실내 나들이 후보로 묶기 좋다.',
    address: '인천광역시 중구 월미로 294',
    operatingHours: '10:00-18:00',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '예약제 안내가 있는 시기가 있어 방문 전 관람 방식과 회차를 확인하는 편이 안전하다.',
    thumbnailImage: '/images/places/national-incheon-marine-museum.webp',
  },
  {
    id: 'geomdan-prehistory-museum',
    name: '검단선사박물관',
    linkedPostSlugs: ['geomdan-prehistory-museum-parking'],
    region: 'incheon',
    subRegion: '서구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/MU030401',
    naverMapUrl: 'https://map.naver.com/p/entry/place/20108015',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '선사시대 유적과 체험 교육을 중심으로 꾸린 서구 대표 공공 박물관. 어린이 체험전과 가족교육이 자주 연결된다.',
    address: '인천광역시 서구 고산후로121번길 7',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 전시 외에도 어린이 특별체험전과 가족교육 공지가 자주 올라온다.',
    thumbnailImage: '/images/places/geomdan-prehistory-museum.webp',
  },
  {
    id: 'incheon-butterfly-park',
    name: '인천나비공원',
    region: 'incheon',
    subRegion: '부평구',
    category: 'park',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    seasons: ['all-season', 'spring', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.icbp.go.kr/open_content/butterfly/',
    naverMapUrl: 'https://map.naver.com/p/search/인천나비공원',
    verifiedAt: '2026-05-07',
    lastObservedAt: '2026-05-07',
    verificationStatus: 'official_verified',
    description:
      '곤충 생태전시와 야외 생태공원을 함께 둘러보는 부평구 자연학습 공간. 봄·가을 가벼운 생태 나들이로 좋다.',
    address: '인천광역시 부평구 평천로 26-47',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '나비 관찰과 야외 생태 동선은 계절 영향을 받으므로 봄·가을 추천 태그를 함께 둔다.',
    linkedPostSlugs: [],
    thumbnailImage: '/images/places/incheon-butterfly-park.webp',
  },
  {
    id: 'incheon-grand-park-wood-culture-center',
    name: '인천대공원 목재문화체험장',
    region: 'incheon',
    subRegion: '남동구',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/park/',
    naverMapUrl: 'https://map.naver.com/p/search/인천대공원 목재문화체험장',
    verifiedAt: '2026-05-07',
    lastObservedAt: '2026-05-07',
    verificationStatus: 'official_verified',
    description:
      '나무와 목공을 주제로 한 실내 체험 공간. 인천대공원 산책 전후로 예약형 만들기 체험을 붙이기 좋다.',
    address: '인천광역시 남동구 무네미로 236 인천대공원',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '요금 확인 필요',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '체험 프로그램은 예약·재료비 조건이 달라 방문 전 인천대공원 공지 확인이 필요하다.',
    linkedPostSlugs: [],
    thumbnailImage:
      '/images/places/incheon-grand-park-wood-culture-center.webp',
  },
  {
    id: 'sudoguksan-museum-childrens-exhibition',
    name: '수도국산달동네박물관 어린이체험실',
    linkedPostSlugs: ['sudoguksan-museum-childrens-exhibition-parking'],
    region: 'incheon',
    subRegion: '동구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.icdonggu.go.kr/open_content/museum/',
    naverMapUrl: 'https://map.naver.com/p/search/수도국산달동네박물관',
    verifiedAt: '2026-07-13',
    lastObservedAt: '2026-07-13',
    verificationStatus: 'official_verified',
    description:
      '인천의 옛 생활사를 아이 눈높이 체험으로 연결할 수 있는 박물관. 짧은 실내 역사 체험 코스로 적합하다.',
    address: '인천광역시 동구 솔빛로 51',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '요금 확인 필요',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '어린이 체험실 또는 교육 프로그램은 회차·예약 여부가 바뀔 수 있어 박물관 공지를 확인해야 한다.',
    thumbnailImage:
      '/images/places/sudoguksan-museum-childrens-exhibition.webp',
  },
  {
    id: 'incheon-childrens-museum',
    name: '인천어린이박물관',
    linkedPostSlugs: ['incheon-childrens-museum-parking'],
    region: 'incheon',
    subRegion: '미추홀구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://www.michuhol.go.kr/culture/',
    naverMapUrl: 'https://map.naver.com/p/search/인천어린이박물관',
    verifiedAt: '2026-05-07',
    lastObservedAt: '2026-05-07',
    verificationStatus: 'semi_verified',
    description:
      '유아·어린이 눈높이 전시와 체험을 중심으로 운영되는 어린이박물관. 문학경기장권 실내 코스로 묶기 쉽다.',
    address: '인천광역시 미추홀구 매소홀로 618 문학경기장 내',
    operatingHours: '운영시간 확인 필요',
    priceInfo: '요금 확인 필요',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'commercial',
    editorNote:
      '민간 시설이라 운영시간·휴관·가격 재확인이 필요하다. 맘맘 발견 후 지자체 문화관광 정보를 보조 출처로 확인했다.',
    thumbnailImage: '/images/places/incheon-childrens-museum.webp',
  },
  {
    id: 'incheon-grand-park-childrens-zoo',
    name: '인천대공원 어린이동물원',
    region: 'incheon',
    subRegion: '남동구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'outdoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/park/park010214',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'official_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 남동구 무네미로 236 인천대공원 내'
    )}`,
    description:
      '인천대공원 안에서 사막여우·미어캣·원숭이·조류 등을 무료로 관찰하는 야외 어린이동물원. 2026년에는 현장 참여형 동물해설 프로그램도 운영한다.',
    address: '인천광역시 남동구 무네미로 236 인천대공원 내',
    operatingHours:
      '10:00-17:00(16:50 입장 마감) / 월요일·1월 1일·설·추석 당일 휴원',
    priceInfo: '무료',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '공식 페이지가 2026-04-14 재개장과 2026년 5~12월 동물해설 프로그램을 명시한다. 해설은 화~토요일 우천 시 미운영이며 별도 예약 없이 현장 참여한다. 동물 먹이주기는 금지되어 있다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title: '인천 아이랑 가볼만한곳 인천대공원 동물원 주차장 운영 시간',
        href: 'https://blog.naver.com/j__trip__/224310964462',
        sourceLabel: 'Naver Blog',
        description:
          '아이 동반 관람 동선과 현장 분위기를 방문자 관점에서 가늠할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-neulsolgil-park-sheep-ranch',
    name: '늘솔길공원 양떼목장',
    region: 'incheon',
    subRegion: '남동구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'outdoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://biz.namdong.go.kr/dong/locinfo/park/parkDetail.do?dong=nonhyeongojan&loc_seq=235327&order=view2',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'official_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 남동구 앵고개로 771 늘솔길근린공원3호'
    )}`,
    description:
      '늘솔길공원 안에서 면양을 가까이 관찰하고 편백숲·숲속놀이터까지 함께 이용하는 무료 야외 나들이 장소. 무장애 숲길이 있어 유아 동반 산책을 붙이기 좋다.',
    address: '인천광역시 남동구 앵고개로 771 늘솔길근린공원3호',
    operatingHours:
      '4-9월 09:30-17:30 / 10-3월 09:30-17:00 / 우천 시 양떼목장 관람 불가',
    priceInfo: '무료',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: false,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '남동구 공식 시설 페이지와 늘솔길숲 공식 시설 페이지에서 양떼목장 운영을 확인했다. 공식 페이지마다 진입 주소와 시간이 조금 달라 주소 기반 지도 검색과 방문 전 당일 안내 확인이 필요하다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title:
          '주말 아이랑 가기좋은 곳 인천 늘솔길공원 양떼목장 장미원 먹이 주차 꿀팁',
        href: 'https://blog.naver.com/blair_____/224295609803',
        sourceLabel: 'Naver Blog',
        description:
          '아이와 둘러본 양떼목장·장미원·주차 동선을 가볍게 참고할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-wolmi-traditional-garden-animal-zone',
    name: '월미공원 한국전통정원 동물체험존',
    region: 'incheon',
    subRegion: '제물포구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'outdoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://itour.incheon.go.kr/thmtour/rcmdtour/detail.do?cotId=ITA21121416220183689',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'semi_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 제물포구 북성동1가 75-1 월미공원 한국전통정원'
    )}`,
    description:
      '월미공원 한국전통정원을 산책하며 사슴과 토끼를 관찰할 수 있는 무료 야외 동물 구역. 물범카·전망대와 함께 월미도 가족 코스로 묶기 좋다.',
    address: '인천광역시 제물포구 북성동1가 75-1 월미공원 한국전통정원',
    operatingHours: '하절기 09:00-18:00 / 동절기 09:00-17:00',
    priceInfo: '무료',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '인천관광공사 페이지가 2026-06-12 수정본에서 사슴·토끼 동물체험존과 운영시간을 명시한다. 공원 1차 페이지는 동물 구역을 별도 안내하지 않아 개체·먹이 체험 여부는 방문 전 확인한다. 2026-07-01 출범한 제물포구 기준 주소다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title:
          '인천 월미공원 나들이│아이들과 즐기는 물범카·토끼·사슴 체험 후기',
        href: 'https://blog.naver.com/sweetbandi/224009458384',
        sourceLabel: 'Naver Blog',
        description:
          '아이와 물범카·동물 구역을 함께 이용한 방문 흐름을 참고할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-sorae-wetland-ecological-park',
    name: '소래습지생태공원',
    region: 'incheon',
    subRegion: '남동구',
    category: 'park',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    seasons: ['all-season', 'spring', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/park/park010301',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'official_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 남동구 소래로154번길 77'
    )}`,
    description:
      '실내 생태전시관에서 갯벌 생물을 배우고 야외 관찰대에서 철새와 습지 생물을 찾는 공공 생태공원. 유아에게는 짧은 전시관·관찰데크 코스로 압축하기 좋다.',
    address: '인천광역시 남동구 소래로154번길 77',
    operatingHours:
      '생태전시관 10:00-18:00(동절기 17:30까지) / 월요일·법정 공휴일 다음날 등 휴관',
    priceInfo: '무료 / 주차 유료',
    feedingRoom: false,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '개인은 현장 관람 가능하고 단체는 사전예약이 필요하다. 야외 철새·갯벌 관찰은 날씨와 계절 영향을 받으며 rainFriendly는 실내 전시관을 기준으로 한다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title: '소래습지생태공원 갯벌체험 인천 아이와 가볼만한곳',
        href: 'https://blog.naver.com/euna841006/223971182953',
        sourceLabel: 'Naver Blog',
        description:
          '아이와 갯벌·습지 동선을 둘러본 방문 흐름을 참고할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-spoonbill-ecology-learning-center',
    name: '인천광역시 저어새 생태학습관',
    region: 'incheon',
    subRegion: '남동구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'both',
    seasons: ['all-season'],
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl: 'https://bfs-ecocenter.kr/sub/sub_0501.php',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'official_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 남동구 능허대로 562'
    )}`,
    description:
      '저어새와 이동성 물새를 주제로 전시·환경교육·자유 탐조를 운영하는 생태학습관. 신분증을 지참하면 정해진 시간에 쌍안경을 빌려 승기천과 앞마당의 새를 관찰할 수 있다.',
    address: '인천광역시 남동구 능허대로 562',
    operatingHours:
      '월-토 09:00-18:00(점심시간 12:00-13:00) / 공휴일·대체공휴일 등 휴관',
    priceInfo: '자유 탐조 무료 / 프로그램별 신청 조건 확인 필요',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '자유 탐조는 별도 예약 없이 가능하지만 쌍안경 대여에는 신분증이 필요하다. 가족 프로그램·학교 교육은 별도 신청제다. rainFriendly는 실내 학습관 이용 기준이며 실제 탐조는 날씨 영향을 받는다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title: '2026 저어새 생일잔치_저어새 캐릭터 공모전 수상',
        href: 'https://blog.naver.com/ttbcub/224288811261',
        sourceLabel: 'Naver Blog',
        description:
          '가족 행사 참여 맥락과 학습관 현장 분위기를 가볍게 확인할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-daeijakdo-marine-ecology-center',
    name: '대이작도 해양생태관',
    linkedPostSlugs: ['incheon-daeijakdo-marine-ecology-center-parking'],
    region: 'incheon',
    subRegion: '옹진군',
    category: 'museum',
    themes: ['animal'],
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21121616000881406',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'semi_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 옹진군 자월면 대이작로159번길 6'
    )}`,
    description:
      '대이작도 주변의 물고기·갯벌·해양생태와 섬 지형을 전시와 VR로 살펴보는 무료 생태관. 섬 체류 일정에서 날씨가 좋지 않을 때 넣기 좋은 짧은 실내 코스다.',
    address: '인천광역시 옹진군 자월면 대이작로159번길 6',
    operatingHours: '10:00-14:00 / 화요일·목요일 휴관',
    priceInfo: '무료',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '인천투어 페이지가 2026-03-03 갱신본에서 시간·휴관일·무료입장·체험 프로그램을 안내한다. 도서 지역이므로 여객선 결항, 계절 운영, 현장 사정에 대비해 출항 전 전화 확인이 필요하다.',
    externalBlogLinks: [
      {
        title:
          "인천 섬여행! '옹진군 대이작도 해양생태관' 대이작도를 그대로 담은 풀스크린 디지털 영상 관람",
        href: 'https://blog.naver.com/kangkanghee00/224065169363',
        sourceLabel: 'Naver Blog',
        description:
          '해양생태관의 전시·영상 관람 흐름을 방문자 관점에서 확인할 수 있는 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-masian-tidal-flat-experience',
    name: '마시안 갯벌 체험장',
    region: 'incheon',
    subRegion: '영종구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'outdoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012115265412706',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'semi_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 영종구 마시란로 107-8'
    )}`,
    description:
      '영종도 마시안 갯벌에서 동죽·소라 등 갯벌 생물을 찾아보고 조개를 채집하는 어촌계 체험장. 현장에서 장화·호미 등을 빌릴 수 있지만 물때와 준비물을 먼저 확인해야 한다.',
    address: '인천광역시 영종구 마시란로 107-8',
    operatingHours:
      '물때에 따라 변동(고조 3시간 후부터 다음 고조 3시간 전) / 당일 체험시간 확인 필요',
    priceInfo: '유료 / 연령·장비 대여별 요금 변동, 공식 일정 확인 필요',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 150,
    operatorType: 'non-profit',
    editorNote:
      '마시안마을 어촌계 운영 시설로 인천투어와 한국어촌어항공단 바다여행에 현재 등재되어 있다. 체험은 현장 접수 안내가 있으나 성수기에는 사전 문의가 안전하다. 2026-07-01 출범한 영종구 기준 주소다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title:
          '[인천] 서울에서 가까운 아이랑 갯벌체험 추천, 마시안 해변 갯벌체험',
        href: 'https://blog.naver.com/onaive/224333388981',
        sourceLabel: 'Naver Blog',
        description:
          '아이 동반 갯벌 체험의 준비물과 현장 흐름을 가늠하기 좋은 최근 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-yeongam-fishing-village-experience',
    name: '영암어촌계 체험장',
    region: 'incheon',
    subRegion: '옹진군',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'outdoor',
    seasons: ['spring', 'summer', 'fall'],
    priceType: 'paid',
    reservationRequired: true,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl:
      'https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=APD21120710052328606',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'semi_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 옹진군 영흥면 영흥서로446번길 46'
    )}`,
    description:
      '영흥도 수해해변의 혼합갯벌에서 바지락·굴·박하지·고둥 등을 관찰하고 채집하는 어촌계 체험장. 물때에 따라 조개잡이와 낚시 경험이 달라져 사전 문의가 필수적이다.',
    address: '인천광역시 옹진군 영흥면 영흥서로446번길 46',
    operatingHours: '시기·물때별 상이 / 사전 문의 및 접수 필요',
    priceInfo: '유료 / 체험 종류·시기별 요금 확인 필요',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: false,
    stayMinutes: 150,
    operatorType: 'non-profit',
    editorNote:
      '인천투어가 2026-05-23 수정본에서 주소·주차·계절별 운영을 안내하고 한국어촌어항공단 바다여행 현재 목록에도 영암마을이 노출된다. 외부인은 영암어촌계 체험객으로 접수해야 하므로 예약 필요를 보수적으로 true로 둔다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title: '[인천 아이랑] 영암어촌계ㅣ 갯벌체험 조개캐기',
        href: 'https://blog.naver.com/jjj99s2/223916792563',
        sourceLabel: 'Naver Blog',
        description:
          '아이와 조개를 캐는 체험 동선과 현장 분위기를 확인할 수 있는 방문 후기입니다.',
      },
    ],
  },
  {
    id: 'incheon-zoobugs-indoor-zoo',
    name: '실내 동물원 쥬벅스',
    region: 'incheon',
    subRegion: '남동구',
    category: 'experience',
    themes: ['animal'],
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    seasons: ['all-season'],
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://leisure-web.yanolja.com/leisure/10317474',
    verifiedAt: '2026-07-10',
    lastObservedAt: '2026-07-10',
    verificationStatus: 'semi_verified',
    naverMapUrl: `https://map.naver.com/p/search/${encodeURIComponent(
      '인천광역시 남동구 서창남순환로216번길 20 승연프라자 2층 204·205호'
    )}`,
    description:
      '서창동에서 여러 종의 동물을 실내에서 관찰하고 일부 교감 활동을 경험하는 유료 생태 체험 공간. 날씨 영향을 덜 받아 유아·초등 저학년 실내 나들이 후보로 쓰기 좋다.',
    address:
      '인천광역시 남동구 서창남순환로216번길 20 승연프라자 2층 204·205호',
    operatingHours: '매일 10:00-19:00(매표 마감 18:00) / 연중무휴 안내',
    priceInfo:
      '2026 NOL 판매 기준 평일 대인 12,000원·소인 15,000원 / 주말·공휴일 대인 13,000원·소인 17,000원 / 18개월 미만 증빙 시 무료',
    feedingRoom: false,
    strollerFriendly: false,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'NOL 상품 유효기간과 판매기간이 2026-12-31까지이며 당일 구매·당일 사용, 운영시간, 주소, 주차, 유모차 탑승 관람 불가를 안내한다. 민간 시설이라 가격과 동물 체험 구성은 방문 전 재확인한다.',
    linkedPostSlugs: [],
    externalBlogLinks: [
      {
        title: '인천 서창 실내동물원 아이와함께 가볼만한 곳 요즘핫플 쥬벅스',
        href: 'https://blog.naver.com/nimost/224329258899',
        sourceLabel: 'Naver Blog',
        description:
          '아이와 실내 동물 공간을 둘러본 최근 방문 흐름을 참고할 수 있는 후기입니다.',
      },
    ],
  },
] satisfies PlaceSource[];
