import type { PlaceSource } from '../../../types/place-source.ts';

const INCHEON_DREAM_CENTER_SOURCE_URL =
  'https://www.incheon.go.kr/icbenefit/ICB020201/?curPage=5&srchField=%EB%B3%B4%EC%9C%A1%EA%B5%90%EC%9C%A1&srchSupport=&srchUserType=&srchWord=';

export const INCHEON_PLACES = [
  {
    id: 'incheon-oktokki-space-center',
    name: '옥토끼우주센터',
    region: 'incheon',
    subRegion: '강화군',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'both',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.oktokki.com/about/fees',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%98%A5%ED%86%A0%EB%81%BC%EC%9A%B0%EC%A3%BC%EC%84%BC%ED%84%B0%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EA%B0%95%ED%99%94%EA%B5%B0%20%EB%B6%88%EC%9D%80%EB%A9%B4%20%EA%B0%95%ED%99%94%EB%8F%99%EB%A1%9C%20403',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '우주과학 전시와 체험, 야외 놀이시설을 함께 이용하는 강화군 민간 우주과학 테마파크.',
    address: '인천광역시 강화군 불은면 강화동로 403',
    operatingHours: '평일 10:00-17:30 / 주말·공휴일 09:30-19:00',
    priceInfo: '24~36개월 미만 13,000원 / 36개월~12세 18,800원 / 13세 이상 19,800원 / 24개월 미만 무료',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
  },
  {
    id: 'incheon-naughty-child-cheongna',
    name: '너티차일드 청라점',
    region: 'incheon',
    subRegion: '서구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.naughtychild.co.kr/cheongna',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%84%88%ED%8B%B0%EC%B0%A8%EC%9D%BC%EB%93%9C%20%EC%B2%AD%EB%9D%BC%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EC%84%9C%EA%B5%AC%20%EC%B2%AD%EB%9D%BC%EC%97%90%EB%A9%94%EB%9E%84%EB%93%9C%EB%A1%9C%2079%20%EC%BB%A4%EB%82%BC%EC%97%90%EB%B9%84%EB%89%B4%20%EC%A7%80%ED%95%981%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '청라 커낼에비뉴 지하에 있는 프리미엄 키즈 테마파크. 카트, 볼풀, 낚시놀이 등 대형 키즈카페 성격이 강하다.',
    address: '인천광역시 서구 청라에메랄드로 79 커낼에비뉴 지하1층',
    operatingHours: '10:30-20:30',
    rainFriendly: true,
    stayMinutes: 150,
    operatorType: 'commercial',
  },
  {
    id: 'incheon-champion-1250-guwol-traders',
    name: '챔피언1250 트레이더스 구월점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'kids-cafe',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://news.nate.com/view/20250904n07092',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%B1%94%ED%94%BC%EC%96%B81250%20%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EC%8A%A4%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EB%82%A8%EB%8F%99%EA%B5%AC%20%EB%A7%A4%EC%86%8C%ED%99%80%EB%A1%9C%20759%20%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EC%8A%A4%20%ED%99%80%EC%84%B8%EC%9D%BC%ED%81%B4%EB%9F%BD%20%EA%B5%AC%EC%9B%94%EC%A0%90%201%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '트레이더스 구월점 1층 입점 신호가 있는 키즈 테마파크 후보. 스카이라인과 대형 어트랙션 중심으로 소개됐다.',
    address: '인천광역시 남동구 매소홀로 759 트레이더스 홀세일클럽 구월점 1층',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote: '보도자료 기반 후보라 발행 전 공식 예약 링크 또는 전화 확인이 필요하다.',
  },
  {
    id: 'incheon-monster-park-guwol',
    name: '몬스터파크 구월점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'semi-official',
    sourceUrl: 'https://monster-park.com/',
    naverMapUrl: 'https://map.naver.com/p/search/%EB%AA%AC%EC%8A%A4%ED%84%B0%ED%8C%8C%ED%81%AC%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C%20%EB%82%A8%EB%8F%99%EA%B5%AC%20%EC%98%88%EC%88%A0%EB%A1%9C%20198%20%ED%99%88%ED%94%8C%EB%9F%AC%EC%8A%A4%20%EA%B5%AC%EC%9B%94%EC%A0%90%20%EC%A7%80%ED%95%983%EC%B8%B5',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '시간 무제한형 실내 테마파크 콘셉트의 구월동 대형 키즈카페 후보. 브랜드 공식 페이지와 구월점 운영 신호를 함께 확인했다.',
    address: '인천광역시 남동구 예술로 198 홈플러스 구월점 지하3층',
    rainFriendly: true,
    stayMinutes: 180,
    operatorType: 'commercial',
    editorNote: '지점 공식 상세가 약해 발행 전 전화 확인이 필요하다.',
  },
  {
    id: 'incheon-dinosaur-world',
    name: '공룡월드 인천점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'kids-cafe',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: false,
    sourceType: 'semi-official',
    sourceUrl:
      'https://travel.interpark.com/tna/products/b075a045-0eba-47a0-82db-01000367d6ae',
    naverMapUrl: 'https://map.naver.com/p/search/%EA%B3%B5%EB%A3%A1%EC%9B%94%EB%93%9C%20%EC%9D%B8%EC%B2%9C%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'semi_verified',
    description:
      '공룡 전시와 공연, 키즈카페형 놀이를 함께 묶은 인천권 공룡 테마 실내 공간. 공룡을 좋아하는 유아·초등 저학년 나들이 후보로 적합하다.',
    priceInfo: '유료 / 온라인 입장권 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      'NOL 인터파크 판매 페이지로 운영 신호를 확인했다. 상세 주소, 주차, 공연 회차는 발행 전 재확인 필요.',
  },
  {
    id: 'incheon-zoorarium-cheongna',
    name: '쥬라리움 청라점',
    region: 'incheon',
    subRegion: '서구',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://zoorarium.com/cheongna',
    naverMapUrl: 'https://map.naver.com/p/search/%EC%A5%AC%EB%9D%BC%EB%A6%AC%EC%9B%80%20%EC%B2%AD%EB%9D%BC%EC%A0%90',
    verifiedAt: '2026-05-04',
    lastObservedAt: '2026-05-04',
    verificationStatus: 'official_verified',
    description:
      '실내 동물원과 키즈카페 성격을 함께 가진 동물교감형 테마 공간. 날씨 영향을 덜 받고 동물 먹이주기·관찰 동선을 구성하기 좋다.',
    priceInfo: '유료 / 지점 공식 안내 기준 변동',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'commercial',
    editorNote:
      '공식 청라점 페이지를 기준으로 넣었다. 동물 체험 운영, 요금, 휴무는 방문 전 공식 안내를 재확인해야 한다.',
  },
  {
    id: 'incheon-aisarang-dream-center-jung-gu-1',
    name: '아이사랑꿈터 중구 1호점',
    region: 'incheon',
    subRegion: '중구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1407229169',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자와 영유아가 함께 머무는 공공 실내 놀이공간. 영종 생활권에서 짧게 들르기 좋은 영아 친화 거점이다.',
    address: '인천 중구 신도시남로 15 103동 104호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공식 포털에 운서동 지점명과 전화가 노출된다. 회차와 프로그램 대상은 방문 전 다시 확인하는 편이 안전하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-dong-gu-1',
    name: '아이사랑꿈터 동구 1호점',
    region: 'incheon',
    subRegion: '동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1877329928',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '보호자 동반 영유아를 위한 공공 놀이공간. 주민행복센터 안에 있어 동네 육아 동선에 넣기 쉽다.',
    address: '인천 동구 염전로40번길 70 주민행복센터 2층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '주민행복센터 연계형 지점이다. 세부 운영 시간보다는 프로그램 공지 중심으로 확인하는 편이 좋다.',
  },
  {
    id: 'incheon-aisarang-dream-center-michuhol-gu-1',
    name: '아이사랑꿈터 미추홀구 1호점',
    region: 'incheon',
    subRegion: '미추홀구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1057272282',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '공동주택 생활권 안에서 이용할 수 있는 공공 영유아 놀이공간. 짧은 체류 위주의 실내 육아 쉼터로 쓰기 좋다.',
    address:
      '인천 미추홀구 숙골로112번길 12 도화서희스타힐스 크루즈시티 B103-2호',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '도화권 공동주택 상가형 지점이다. 외부 방문자 주차 여부는 이번 차수에서 확인하지 못했다.',
  },
  {
    id: 'incheon-aisarang-dream-center-yeonsu-gu-2',
    name: '아이사랑꿈터 연수구 2호점',
    region: 'incheon',
    subRegion: '연수구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1810350999',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '송도 공동주택 생활권에서 이용하기 좋은 공공 영유아 놀이공간. 날씨에 덜 영향을 받는 실내 육아 동선 후보다.',
    address: '인천 연수구 송도문화로28번길 81 송도 더샾그린스퀘어 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '송도 공동주택형 지점이다. 프로그램별 연령 기준이 달라 신청 전 대상 확인이 필요하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-namdong-gu-4',
    name: '아이사랑꿈터 남동구 4호점',
    region: 'incheon',
    subRegion: '남동구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1276800679',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '남동구 에코메트로 생활권에서 접근하기 쉬운 공공 놀이공간. 영유아와 보호자가 함께 머물기 좋은 소규모 실내 공간이다.',
    address:
      '인천 남동구 논현로 106 에코메트로한화꿈에그린 608동 B1 관리사무소 옆',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '공동주택 단지형 지점이라 외부 주차 가능 여부보다 프로그램 접근성을 우선 확인하는 편이 좋다.',
  },
  {
    id: 'incheon-aisarang-dream-center-gyeyang-gu-4',
    name: '아이사랑꿈터 계양구 4호점',
    region: 'incheon',
    subRegion: '계양구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1646319802',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '생활문화센터 안에 들어선 공공 영유아 놀이공간. 짧은 놀이와 부모 휴식 동선을 함께 잡기 쉽다.',
    address: '인천 계양구 장제로 853 계양2동 생활문화센터 4층',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '생활문화센터형 지점이다. 층수 이동이 있어 유모차 동선은 현장 여건을 다시 보는 편이 안전하다.',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-1',
    name: '아이사랑꿈터 서구 1호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/1093768329',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '루원시티권에서 이용하기 좋은 공공 영유아 놀이공간. 생활권 안에서 비 오는 날 대안 동선으로 활용하기 좋다.',
    address: '인천 서구 봉오재1로 36 루원센트럴타운 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '루원시티 공동주택형 지점이다. 공식 포털에는 신현동 표기가 함께 노출된다.',
  },
  {
    id: 'incheon-aisarang-dream-center-seo-gu-4',
    name: '아이사랑꿈터 서구 4호점',
    region: 'incheon',
    subRegion: '서구',
    category: 'public-play',
    ageBands: ['0-12m', '1-3y', '3-6y'],
    indoorOutdoor: 'indoor',
    priceType: 'paid',
    reservationRequired: true,
    parking: false,
    sourceType: 'official',
    sourceUrl: INCHEON_DREAM_CENTER_SOURCE_URL,
    naverMapUrl: 'https://map.naver.com/p/entry/place/572996995',
    verifiedAt: '2026-04-07',
    lastObservedAt: '2026-04-07',
    verificationStatus: 'official_verified',
    description:
      '청라 생활권 보호자와 영유아를 위한 공공 놀이공간. 주민공동시설 기반이라 가까운 실내 육아 거점으로 쓰기 좋다.',
    address: '인천 서구 청라한내로 40 청라호수공원한신더휴 주민공동시설',
    priceInfo: '이용료 1,000원 / 프로그램별 신청',
    rainFriendly: true,
    stayMinutes: 60,
    operatorType: 'public',
    editorNote:
      '청라 공동주택형 지점이다. 프로그램 운영일과 신청 방식은 공식 공지를 다시 확인해야 한다.',
  },
  {
    id: 'incheon-children-science-museum',
    name: '인천어린이과학관',
    region: 'incheon',
    subRegion: '계양구',
    category: 'museum',
    ageBands: ['0-12m', '1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'partial-free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://www.insiseol.or.kr/culture/icsmuseum/introduction/preview.jsp',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19545719',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '영유아 전용 무지개마을 구역이 함께 있는 어린이 과학관. 회차별 예약제로 어린 아이와도 비교적 안정적으로 움직이기 좋다.',
    address: '인천광역시 계양구 방축로21',
    operatingHours: '09:00-18:00 (회차별 사전 온라인 예약제)',
    priceInfo:
      '어린이·청소년 2,000원 / 성인 4,000원 / 보호자 동반 만 6세 이하 무료',
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '공식 사이트에 예약, 편의시설, 주차장안내 메뉴가 함께 노출된다. 상설전시관은 회차별 사전예약제로 운영된다.',
  },
  {
    id: 'incheon-student-science-museum',
    name: '인천학생과학관',
    region: 'incheon',
    subRegion: '중구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: false,
    sourceType: 'official',
    sourceUrl:
      'https://science.ice.go.kr/msi/cntntsService.do?menuId=MNU_0000000000000082',
    naverMapUrl: 'https://map.naver.com/p/entry/place/19801527',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '무료로 가볍게 들르기 좋은 과학 체험 공간. 개별 관람은 현장 접수라 영종권 실내 나들이 후보로 묶기 쉽다.',
    address: '인천광역시 중구 영종대로 277번길 74-10',
    operatingHours: '화~일 운영 / 개별 관람 현장 접수',
    priceInfo: '무료',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '개별 관람은 현장 접수, 단체 관람은 사전 예약 승인 후 이용한다. 천체투영실은 6세 이상 중심이다.',
  },
  {
    id: 'oktokki-space-center',
    name: '옥토끼우주센터',
    region: 'incheon',
    subRegion: '강화군',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y', 'all'],
    indoorOutdoor: 'both',
    priceType: 'partial-free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.oktokki.com/about/fees',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12090933',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '우주과학 테마 전시와 야외 체험 동선을 함께 묶은 강화 대표 가족형 시설. 하루 일정으로 넉넉하게 잡는 편이 잘 맞는다.',
    address: '인천광역시 강화군 불은면 강화동로 403',
    operatingHours: '평일 10:00-17:30 / 주말·공휴일 09:30-19:00',
    priceInfo:
      '24~36개월 미만 13,000원 / 36개월~12세 18,800원 / 13세 이상 19,800원 / 24개월 미만 무료',
    rainFriendly: false,
    stayMinutes: 240,
    operatorType: 'commercial',
    editorNote:
      '24개월 미만은 무료지만 일부 시설 이용 제한이 있을 수 있다. 야외 체험 비중이 있어 날씨 영향을 고려하는 편이 좋다.',
  },
  {
    id: 'ganghwa-history-museum',
    name: '강화역사박물관',
    region: 'incheon',
    subRegion: '강화군',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ganghwa.go.kr/open_content/museum_history/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12442027',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '강화도 선사부터 근현대까지 지역 역사를 한 번에 훑기 좋은 공공 박물관. 근처 자연사박물관과 함께 묶기 좋다.',
    address: '인천광역시 강화군 하점면 강화대로 994-19',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '강화권 공공 박물관 동선으로 자연사박물관과 함께 묶기 좋다.',
  },
  {
    id: 'ganghwa-natural-history-museum',
    name: '강화자연사박물관',
    region: 'incheon',
    subRegion: '강화군',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.ganghwa.go.kr/open_content/museum_natural/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37027622',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '공룡과 화석, 자연 생태 전시를 중심으로 아이들이 흥미를 느끼기 쉬운 강화권 자연사 박물관.',
    address: '인천광역시 강화군 하점면 강화대로 994-33',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '역사박물관과 가까워 강화권 실내 코스로 연계하기 쉽다.',
  },
  {
    id: 'gyeyang-fortress-museum',
    name: '계양산성박물관',
    region: 'incheon',
    subRegion: '계양구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://museum.gyeyang.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1464948902',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '산성 유적과 지역 역사를 어린이 눈높이 전시로 풀어낸 산성 전문 박물관. 계양산 나들이와 연결하기 좋다.',
    address: '인천광역시 계양구 계양산로 101',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 75,
    operatorType: 'public',
    editorNote:
      '전시 관람 뒤 계양산성 주변 산책 코스와 함께 묶는 동선이 자연스럽다.',
  },
  {
    id: 'national-institute-of-biological-resources',
    name: '국립생물자원관',
    region: 'incheon',
    subRegion: '서구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.nibr.go.kr/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/12338771',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '생물 표본과 생태 전시를 중심으로 자연 관찰 흥미를 키우기 좋은 국립 기관 전시관.',
    address: '인천광역시 서구 환경로 42 국립생물자원관',
    operatingHours: '09:30-17:30 (월요일 휴관)',
    feedingRoom: true,
    strollerFriendly: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '전시 규모가 커서 초등 저학년까지 폭넓게 묶기 좋다.',
  },
  {
    id: 'incheon-safety-experience-center',
    name: '인천국민안전체험관',
    region: 'incheon',
    subRegion: '서구',
    category: 'experience',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/119safe/index',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1649366728',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '재난과 생활안전 주제를 실습형으로 체험하는 대형 안전 체험관. 비 오는 날 실내 교육형 나들이로 잘 맞는다.',
    address: '인천광역시 서구 봉오재1로 120',
    operatingHours: '09:00-18:00 (월요일 휴관, 사전예약제)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote: '예약제 운영이라 회차를 먼저 잡고 움직이는 편이 안전하다.',
  },
  {
    id: 'national-museum-of-world-writing',
    name: '국립세계문자박물관',
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.mow.or.kr/kor/',
    naverMapUrl: 'https://map.naver.com/p/entry/place/37162865',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '문자와 기록 문화를 시각적으로 풀어낸 국립 박물관. 송도 실내 문화 동선으로 묶기 좋다.',
    address: '인천광역시 연수구 센트럴로 217 국립세계문자박물관',
    operatingHours: '10:00-18:00 (월요일 휴관)',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 전시 중심으로 가볍게 보기 좋고, 송도권 다른 실내 시설과 연계하기 쉽다.',
  },
  {
    id: 'incheon-metropolitan-city-museum',
    name: '인천광역시립박물관',
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/index',
    naverMapUrl: 'https://map.naver.com/p/entry/place/11620569',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '인천 지역사 전체를 폭넓게 다루는 대표 공공 박물관. 송도권 역사·전시 코스로 기본축이 되는 시설이다.',
    address: '인천광역시 연수구 청량로160번길 26 인천시립박물관',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote: '연수구 문화벨트 박물관 동선의 중심으로 묶기 좋다.',
  },
  {
    id: 'incheon-urban-history-museum',
    name: '인천도시역사관',
    region: 'incheon',
    subRegion: '연수구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/MU050101',
    naverMapUrl: 'https://map.naver.com/p/entry/place/13294480',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '인천 도시 형성과 생활 변화를 중심으로 구성한 역사 전시관. 어린이 특별전이 함께 열리는 편이라 가족 관람에 무난하다.',
    address: '인천광역시 연수구 인천타워대로 238',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 75,
    operatorType: 'public',
    editorNote:
      '송도권 실내 문화시설을 묶는 코스에서 박물관 입문용으로 쓰기 좋다.',
  },
  {
    id: 'national-incheon-marine-museum',
    name: '국립인천해양박물관',
    region: 'incheon',
    subRegion: '중구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: true,
    parking: true,
    sourceType: 'official',
    sourceUrl:
      'https://inmm.or.kr/page/ko/selectPage.do?menuSeq=3350&pageSeq=3716',
    naverMapUrl: 'https://map.naver.com/p/entry/place/1648472832',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '해양사와 항만 문화를 현대적으로 풀어낸 국립 박물관. 월미권 실내 나들이 후보로 묶기 좋다.',
    address: '인천광역시 중구 월미로 294',
    operatingHours: '10:00-18:00',
    feedingRoom: true,
    rainFriendly: true,
    stayMinutes: 120,
    operatorType: 'public',
    editorNote:
      '예약제 안내가 있는 시기가 있어 방문 전 관람 방식과 회차를 확인하는 편이 안전하다.',
  },
  {
    id: 'geomdan-prehistory-museum',
    name: '검단선사박물관',
    region: 'incheon',
    subRegion: '서구',
    category: 'museum',
    ageBands: ['1-3y', '3-6y', '6-10y'],
    indoorOutdoor: 'indoor',
    priceType: 'free',
    reservationRequired: false,
    parking: true,
    sourceType: 'official',
    sourceUrl: 'https://www.incheon.go.kr/museum/MU030401',
    naverMapUrl: 'https://map.naver.com/p/entry/place/20108015',
    verifiedAt: '2026-04-08',
    lastObservedAt: '2026-04-08',
    verificationStatus: 'official_verified',
    description:
      '선사시대 유적과 체험 교육을 중심으로 꾸린 서구 대표 공공 박물관. 어린이 체험전과 가족교육이 자주 연결된다.',
    address: '인천광역시 서구 고산후로121번길 7',
    operatingHours: '09:00-18:00 (월요일 휴관)',
    rainFriendly: true,
    stayMinutes: 90,
    operatorType: 'public',
    editorNote:
      '상설 전시 외에도 어린이 특별체험전과 가족교육 공지가 자주 올라온다.',
  },
] satisfies PlaceSource[];
